<style type="text/css">

	.secondaires {
		background: #FFF;
		border-width: 0;
	}
	
</style>

<?php $vide = $scene->transitions_secondaires == null || $scene->transitions_secondaires->count() == 0; ?>

<button class="btn secondaires popover-link popover-secondaires" 
	data-toggle="popover"
	data-placement="right" 
	data-html="true" 
	data-title="Transitions secondaires" 
	data-content='
		<?php if (!$vide) : ?>
			<ul class="nav nav-list">
				<?php foreach ($scene->transitions_secondaires as $transition) : ?>
				<li>
					[<?php echo $this->escapeHtml($transition->semantique->semantique); ?>]
					"<?php echo $this->escapeHtml($transition->narration); ?>"
					<a href="<?php echo $this->url('scene/voirScene', array('id' => $transition->scene_destination->id)) ?>"> <i class="icon-arrow-right"></i> <?php echo $this->escapeHtml($transition->scene_destination->titre); ?>
					</a>
				</li>
				<li class="divider"></li>
				<?php endforeach; ?>
			</ul>
		<?php else :?>
			Aucune transition secondaire ne part de cette scène.
		<?php endif;?>' 
	
	data-trigger="manual" 
	title="" > 
	<?php if (!$vide) : ?>
		<i class="icon-arrow-right"></i><br>
		<i class="icon-arrow-right"></i><br>
		<i class="icon-arrow-right"></i>
	<?php else :?>
		<i class="icon-arrow-right icon-muted"></i><br>
		<i class="icon-arrow-right icon-muted"></i><br>
		<i class="icon-arrow-right icon-muted"></i>
	<?php endif;?>
</button>
