<style type="text/css">

	.secondaires {
		background: #FFF;
		border-width: 0;
	}
	
</style>

<button class="btn secondaires popover-link" 
            data-toggle="popover" 
            data-placement="right" 
            data-html="true"
            data-title="<h5>Transitions secondaires</h5>"
            data-content='
                <ul class="nav nav-list">
                	<li class="nav-header strong">Vers scènes recommandées</li>
		        	<li>
		        		<span class="edit2 CursorPointer"
                        	data-url="#"
                        	data-name="narration" 
                        	data-type="textarea" 
                        	data-pk="1"> Texte de la transition
                        </span>
                        <span href="#" 
                       		class="edit2 CursorPointer selectSemantiques" 
                       		data-value=""
                       		data-url="">
                        		[Sémantique] 
                    	</span>
                        <a href="#"> <i class="icon-arrow-right"></i> Titre de la scène destination</a>
                    </li>
		        	<li class="nav-header strong">Vers scènes secondaires</li>
		        	<li>
		        		<span class="edit2 CursorPointer"
                        	data-url="#"
                        	data-name="narration" 
                        	data-type="textarea" 
                        	data-pk="1"> Texte de la transition
                        </span>
                        <span href="#" 
                       		class="edit2 CursorPointer selectSemantiques" 
                       		data-value=""
                       		data-url="">
                        		[Sémantique] 
                    	</span>
                        <a href="#"> <i class="icon-arrow-right"></i> Titre de la scène destination</a>
                    </li>
                    <li class="divider"></li>
		        	<li>
		        		<span class="edit2 CursorPointer"
                        	data-url="#"
                        	data-name="narration" 
                        	data-type="textarea" 
                        	data-pk="1"> Texte de la transition
                        </span>
                        <span href="#" 
                       		class="edit2 CursorPointer selectSemantiques" 
                       		data-value=""
                       		data-url="">
                        		[Sémantique] 
                    	</span>
                        <a href="#"> <i class="icon-arrow-right"></i> Titre de la scène destination</a>
                    </li>
                    <li class="divider"></li>
		        	<li>
		        		<span class="edit2 CursorPointer"
                        	data-url="#"
                        	data-name="narration" 
                        	data-type="textarea" 
                        	data-pk="1"> Texte de la transition
                        </span>
                        <span href="#" 
                       		class="edit2 CursorPointer selectSemantiques" 
                       		data-value=""
                       		data-url="">
                        		[Sémantique] 
                    	</span>
                        <a href="#"> <i class="icon-arrow-right"></i> Titre de la scène destination</a>
                    </li>
                </ul>' 
            data-trigger="manual"
            title="" >
            <i class="icon-arrow-right"></i>
    </button>
