<?php
$title = $Parcours->titre;
$this->headTitle($title);
?>

<div class="page-header">
	<div class="row-fluid">
		<div class="span9">
			<h1> <?php echo $this->escapeHtml($title); ?></h1>
		</div>
		<div class="span3">
			<a href="<?php echo $this->url('parcours/voir', array('id' => $Parcours->id)) ?>" 
				class="btn btn-primary btn-block"> 
				<i class="icon-reply"></i> Retour au parcours
			</a>
		</div>
    </div>
</div>

<script type="text/vnd.graphviz" id="cluster">
digraph "G" { <?php echo $dot ; ?> }
</script>

<?php
 echo $this->headScript()->appendFile($this->basePath() . '/js/canviz/viz.js');
?>

<script>
      
      function inspect(s) {
        return "<pre>" + s.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;") + "</pre>"
      }
      
      function src(id) {
        return document.getElementById(id).innerHTML;
      }
      
      function example(id, format) {
        var result;
        try {
          result = Viz(src(id), format);
          if (format === "svg")
            return result;
          else
            return inspect(result);
        } catch(e) {
          return inspect(e.toString());
        }
      }

      document.body.innerHTML += example("cluster", "svg");

 </script>



