
<html>
<head>
<?php


$this->headScript()->appendFile($this->basePath() . '/js/canviz/prototype.js');
$this->headScript()->appendFile($this->basePath() . '/js/canviz/path.js');
echo $this->headScript()->appendFile($this->basePath() . '/js/canviz/canviz.js');

?>
<script type="text/javascript">

function click_node(node) {
	$('click_output').update('You clicked "' + node + '"');
}

document.observe('dom:loaded', function() {
	new Canviz('canviz', "digraph hello_world {	node [href='javascript:void(click_node('\N'))']	hello:e->world:w}");
});

</script>
</head>
<body>

<div class="graph">
	<div id="canviz"></div>
</div>

<p id="click_output"></p>

<div id="debug_output"></div>

</body>
</html>
