<?php
$title = $Parcours->titre;
$this->headTitle($title);
?>

<div class="page-header">
	<div class="row-fluid">
		<div class="span9">
			<h1> <?php echo $this->escapeHtml($title); ?></h1>
		</div>
		<div class="span3">
			<a href="<?php echo $this->url('parcours/voir', array('id' => $Parcours->id)) ?>" 
				class="btn btn-primary btn-block"> 
				<i class="icon-reply"></i> Retour au parcours
			</a>
		</div>
    </div>
</div>

<script type="text/vnd.graphviz" id="cluster">
digraph "<?php echo $Parcours->titre; ?>" { <?php echo $dot ; ?> }
</script>

<?php
$this->headScript()->appendFile($this->basePath() . '/js/viz.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.panzoom.js');
?>
<style type="text/css">
#panzoom{
  width: 400px;
  height: 800px;
}
</style>
<section class="buttons">
      <button class="zoom-in">Zoom In</button>
      <button class="zoom-out">Zoom Out</button>
      <input type="range" class="zoom-range">
      <button class="reset">Reset</button>
</section>
<div style="overflow: hidden; position: relative;"> 
<div id="panzoom" style="text-align: center" class="span12">
</div>
</div>

<script>
    // 
      $("#panzoom").panzoom({
        $zoomIn: $(".zoom-in"),
        $zoomOut: $(".zoom-out"),
        $zoomRange: $(".zoom-range"),
        $reset: $(".reset")
      });
      
      function inspect(s) {
        return "<pre>" + s.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;") + "</pre>"
      }
      
      function src(id) {
        return document.getElementById(id).innerHTML;
      }
      
      function example(id, format) {
        var result;
        try {
          result = Viz(src(id), format);
          if (format === "svg")
            return result;
          else
            return inspect(result);
        } catch(e) {
          return inspect(e.toString());
        }
      }
      $('#panzoom').html(example("cluster", "svg"));
      //document.body.innerHTML += example("cluster", "svg");

 </script>



