<?php
$title = $Parcours->titre;
$this->headTitle($title);
?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> 
    <small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
    <p><?php echo $Parcours->description;?></p>
</div>


<style type="text/css">
.well{
	margin-bottom: 1px;
}


 .icon-black{
        color:  rgb(51, 51, 51);
        text-decoration: none;
      }

      .voirfond {
        background: #EDEDED;
      }

      .elements{
        text-align: center;
      }
      .elements .element {
        width: 180px;/*
        line-height:100px;*/

        text-align: center;
        padding: 30px 10px 30px 10px;
      }/*
      .shortcuts .shortcut .text {
        line-height:1.2;
  		display:inline-block;
        vertical-align: middle;
        text-align: center;
      }*/
      .liaison {
      	margin:2px;
        width: 188px;
        background: #FFF;
        border-width: 0;

      }


a [class^="icon-"],
a [class*=" icon-"],
a [class^="icon-"]:before,
a [class*=" icon-"]:before {
  display: inline-block;
}


</style>




<?php
//var_dump($Parcours);

?>


<div class="elements">
<?php foreach( ($Parcours->sous_parcours) as $sous_parcours) : ?>



    <a class="btn btn-large element popover-link" href="#"
    data-toggle="popover" 
    data-placement="right" 
    data-html="true" 
    data-content='
    <ul class="nav nav-list">
        <li><a href="<?php echo $this->url('scene/voirScene', array('id' => $sous_parcours->scene_depart->id)) ?>"><i class="icon-eye-open"></i> Voir la scene</a></li>
        <?php if ($this->isAllowed('Parcours') === true) :?>
        <li><a href="#"><i class="icon-pencil"></i> Modifier la scene</a></li>
        <li><a 
                href="#" 
                data-value="<?php echo $this->escapeHtml($sous_parcours->scene_depart->titre) ; ?>" 
                data-url="<?php echo $this->url('scene/removeScene', array('id' => $sous_parcours->scene_depart->id)) ?>"
                class="text-error SupprimerScene" >
                    <i class="icon-trash"></i> Supprimer la scene
            </a>
        </li>
        <li><a href="#"><i class="icon-mail-reply"></i></i> Ajouter une scène avant</a></li>
        <li><a href="#"><i class="icon-mail-forward icon-rotate-180"></i> Ajouter une scène après</a></li>
        <?php endif; ?>
    </ul>
    '
    data-trigger="manual"
    title="" ><span class="text"><?php echo $this->escapeHtml($sous_parcours->scene_depart->titre) ; ?></span></a><br>
<?php

$debut = $sous_parcours->scene_depart->transition_recommandee;


while($debut != null):

?>

    <a class="btn btn-mini liaison popover-link" href="#"
    data-toggle="popover" 
    data-placement="right" 
    data-html="true"
    data-title='<?php echo $this->escapeHtml($debut->semantique->semantique); ?>' 
    data-content='<?php echo $this->escapeHtml($debut->narration); ?><br>
		<ul class="nav nav-list">
            <?php if ($this->isAllowed('Parcours') === true) :?>
		    <li><a href="#" calss="ajScene"><i class="icon-plus"></i> Ajouter une scène</a></li>
		    <li><a href="#"><i class="icon-pencil"></i> Modifier la transition</a></li>
		    <li><a class="text-error" href="#"><i class="icon-trash"></i> Supprimer la transition</a></li>
            <?php endif; ?>
		</ul>
	' 
    data-trigger="manual"
    title="" ><i class="icon-arrow-down icon-large"></i></a><br>


<a class="btn btn-large element popover-link" href="#"
    data-toggle="popover" 
    data-placement="right" 
    data-html="true"
    data-content='
    <ul class="nav nav-list">
        <li><a href="<?php echo $this->url('scene/voirScene', array('id' => $debut->scene_destination->id)) ?>"><i class="icon-eye-open"></i> Voir la scene</a></li>
        <?php if ($this->isAllowed('Parcours') === true) :?>
        <li><a href="#"><i class="icon-pencil"></i> Modifier la scene</a></li>
        <li><a 
                href="#" 
                data-value="<?php echo $this->escapeHtml($debut->scene_destination->titre) ; ?>" 
                data-url="<?php echo $this->url('scene/removeScene', array('id' => $debut->scene_destination->id)) ?>"
                class="text-error SupprimerScene" >
                    <i class="icon-trash"></i> Supprimer la scène
            </a>
        </li>
        <li><a href="#"><i class="icon-mail-reply"></i></i> Ajouter une scène avant</a></li>
        <li><a href="#"><i class="icon-mail-forward icon-rotate-180"></i> Ajouter une scène après</a></li>
        <?php endif; ?>
	</ul>'
    data-trigger="manual"
    title="" ><span class="text"><?php echo $this->escapeHtml($debut->scene_destination->titre) ; ?></span></a><br>

<?php
	$debut = $debut->scene_destination->transition_recommandee;
endwhile;
?>
    <?php if ($this->isAllowed('Parcours') === true) :?>

        <a class="btn btn-mini liaison ajScene" 
        href="#"
        data-url="<?php echo $this->url('scene/ajouterScene') ?>"
        title="" ><i class="icon-plus"></i> Ajouter une scene</a><br>

    <?php endif; ?>

<?php endforeach ; ?>
</div>



<div id="confirmDiv"></div>
<div id="modalDiv"></div>


<?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js'); ?>
<?php $this->inlineScript()->captureStart() ?>
    $(function() {
        $('.popover-link').each(function () {
            $(this).click(function () {
                $(this).popover('show');
            });
        });

    $('body').on('click', function (e) {
        $('.popover-link').each(function () {
            //the 'is' for buttons that triggers popups
            //the 'has' for icons within a button that triggers a popup
            if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
                $(this).popover('hide');
            }
        });
      });
    $(".elements").on("click",".SupprimerScene", function(e){
            var dataURL = $(this).attr('data-url');
            var dataValue = $(this).attr('data-value');
            $('#confirmDiv').confirmModal({
                heading:"Confirmation : suppression d'une scène",
                body:"Êtes-vous sûr de vouloir supprimer définitivement la scène <i>" + dataValue + " </i>?",
                callback: function() {
                     $.post(
                        dataURL,
                        { name: "supprimer" },
                        function() {
                            document.location.reload();
                        }
                    );
                }
            });
        });
    });


    $(".ajScene").on("click", function(e){
            var URL = $(this).attr('data-url');
            $.ajax({
                url: URL,
                type: "POST",
                data:{ name:'ajChamp', submit:'false' }, 
                success:function(response){
                    $('#modalDiv').html('<div id="ChampModal" class="modal">' + response + '</div>').modal();
        
                    $('form.ajChampForm').attr('action', URL);
        
                    //console.info($('form.ajChampForm').attr('action')+'::'+ URL);
                },
                error: function(){
                    alert('Impossible d\'ajouter des champ');
                }
            });
        });
        
        $("#modalDiv").on("click",".ajChampSubmit", function(e){
            var $form = $('.ajChampForm');
            var formatVal = $form.find( 'select[name="format"]' ).val();
            var descriptionVal = $form.find( 'textarea[name="description"]' ).val();
            var labelVal = $form.find( 'input[name="label"]' ).val();
            var URL = $form.attr( 'action' );
        
            $.ajax({
                url: URL,
                type: "POST",
                data:{ name:'ajChamp', submit:'true', format: formatVal, description: descriptionVal, label: labelVal }, 
                success:function(response){
        
                    if(response == 'true') {
                        location.reload();
                    } else {
        
                        $('#modalDiv').html('<div id="ChampModal" class="modal">' + response + '</div>').modal();
                        $('form.ajChampForm').attr('action', URL);
                    }
                },
                error: function(response){
                    alert('Impossible d\'ajouter des champ');
                }
            });
        });

<?php $this->inlineScript()->captureEnd() ?>

























