<?php
$title = 'La collection numérique';
$this->headTitle($title);
?>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/pillbox.css'); ?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<a href="<?php echo $this->url('artefact/ajouter') ?>" class="btn icon-plus btn-primary">Ajouter un artefact</a>
		<a href="<?php echo $this->url('media/ajouter') ?>" class="btn icon-plus btn-primary">Ajouter un média</a>
		<br/><br/>
		<div class="well">
		
			<form id="form-multi" name="form-multi" class="">
			
				<label>Recherche</label>
				
				<div class="input-append">
					<input class="form-titre" type="text" placeholder="Titre" data-type="titre" />
					<button class="btn form-plus-titre" type="button"><i class="icon-plus"> </i></button>
					<!--<button id="form-switch-titre" class="btn" type="button"><i class="icon-refresh"> </i></button>-->
				</div>

				<!-- <br/><br/>
	
				<div class="btn-group">
					<input type="button" class="btn form-button" data-type="type" data-value="artefact" value="Artefact" />
					<input type="button" class="btn form-button" data-type="type" data-value="media" value="Média" />
				</div>-->

				<br/><br/>
				
				<div class="input-append">
					<label>Artefact</label>
					<select class="form-type">
						<option class="type-all" data-type="type" data-value="artefact" >Tous</option>
						<?php 
							foreach ($allTypeArtefact as $typeElement){
								echo '<option data-type="id" data-value="'.$typeElement->id.'" >'.$typeElement->nom.'</option>';
							}
						?>
					</select>
					<button class="btn form-plus-type" type="button"><i class="icon-plus"> </i></button>
				</div>
				
				<br/>
				
				<div class="input-append">
					<label>Média</label>
					<select class="form-type">
						<option class="type-all" data-type="type" data-value="media" >Tous</option>
						<?php 
							foreach ($allTypeMedia as $typeElement){
								echo '<option data-type="id" data-value="'.$typeElement->id.'" >'.$typeElement->nom.'</option>';
							}
						?>
					</select>
					<button class="btn form-plus-type" type="button"><i class="icon-plus"> </i></button>
				</div>
				
				<br/><br/>
				
				<div>
					Tags :
					<div id="form-pillbox" class="pillbox">
						<ul>
						</ul>
					</div>

				</div>
				
				<br/>
				
				<div class="btn-group">
					<button class="btn btn-success form-submit">Rechercher</button>
					<button class="btn btn-danger form-clear">clear</button>
				</div>

			</form>
			
		</div>
	</div>
	
<?php echo $this->CollectionWidget(); ?>

</div>

<a href="<?php echo $this->url('artefact/ajouter') ?>" class="btn icon-plus btn-primary">Ajouter un artefact</a>
<a href="<?php echo $this->url('media/ajouter') ?>" class="btn icon-plus btn-primary">Ajouter un média</a>

<?php $this->headScript()->appendFile($this->basePath() . '/js/pillbox.js') ;?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/dataTables.js') ;?>
