<?php
$title = 'La collection numérique';
$this->headTitle($title);
?>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/pillbox.css'); ?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<a href="<?php echo $this->url('artefact/ajouter') ?>" class="btn icon-plus btn-primary">Ajouter un artefact</a>
<a href="<?php echo $this->url('media/ajouter') ?>" class="btn icon-plus btn-primary">Ajouter un média</a>

<hr>
<div class="well">
<form id="form-multi" name="form-multi" class="">
	<div class="row-fluid">
	
		<div class="span6 input-append">
			<input class="form-titre span10" type="text" placeholder="Titre" data-type="titre" />
			<button class="btn btn-info form-plus-titre" type="button"><i class="icon-plus"> </i></button>
		</div>

		<div class="span3">
			<div class="input-prepend input-append">
				<span class="add-on"><i class="icon-tag"> </i></span>
				<select class="form-type span9">
					<option class="type-all" data-type="type" data-value="artefact" >Tous types d'artefacts</option>
					<?php 
						foreach ($allTypeArtefact as $typeElement){
							echo '<option data-type="id" data-value="'.$typeElement->id.'" >'.$typeElement->nom.'</option>';
						}
					?>
				</select>
				<button class="btn btn-info form-plus-type" type="button"><i class="icon-plus"> </i></button>
			</div>
		</div>
		
		<div class="span3">
			<div class="input-prepend input-append">
				<!-- <label>Média</label> -->
				<span class="add-on"><i class="icon-picture"> </i></span>
				<select class="form-type span9">
					<option class="type-all" data-type="type" data-value="media" >Tous types de médias</option>
					<?php 
						foreach ($allTypeMedia as $typeElement){
							echo '<option data-type="id" data-value="'.$typeElement->id.'" >'.$typeElement->nom.'</option>';
						}
					?>
				</select>
				<button class="btn btn-info form-plus-type" type="button"><i class="icon-plus"> </i></button>
			</div>
		</div>
		
	</div> <!-- /row-fluid -->

	<p>Tags :</p>
	<div id="form-pillbox" class="pillbox" style="width:50%;">
		<ul>
		</ul>
	</div>

	<div class="form-actions">	
		<button id="submit" class="btn btn-primary">Lancer la recherche</button>
	</div>

</form>
</div>
	<?php echo $this->CollectionWidget(); ?>
</div>

<?php $this->headScript()->appendFile($this->basePath() . '/js/pillbox.js') ;?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/dataTables.js') ;?>
