<?php
$title = 'La collection numérique';
$this->headTitle($title);
?>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css'); ?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div>
                <table class="table table-striped table-bordered" id="data">
                    <thead>
                        <tr>
                            <th>Titre</th>
                            <th>Description</th>
                            <th>Type</th>
                            <th>A/M</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="4">En cours de téléchargement</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<a href="<?php echo $this->url('artefact/ajouter') ?>" class="btn icon-plus btn-primary">Ajouter un artefact</a>
<a href="<?php echo $this->url('media/ajouter') ?>" class="btn icon-plus btn-primary">Ajouter un média</a>

<?php $this->headScript()->appendFile($this->basePath() . '/js/dataTables.js') ;?>

<script type="text/javascript">
	var aaData = <?php echo $aaData; ?>;
    ResultSet.paginate(
		{
			"aaData": aaData,
           	"aoColumns": [
	           	           	null,
	           	           	null, 
	           	        	{ "bSortable": false  },
	                     	{ "bSortable": false  }
           	           	 ],
           	"iColumns": 4
		}
	);
</script>
