<?php
$title = "Création d'un nouvel utilisateur";
$this->headTitle();
?>

<ul class="breadcrumb">
	<li><a href="<?php echo $this->url('page') ?>">Accueil</a> <span class="divider">/</span></li>
    <li class="active"> Administration <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('admin/gestion-users') ?>">Gestion des utilisateurs</a> <span class="divider">/</span></li>
    <li class="active"> Création d'un nouvel utilisateur </li>
</ul>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
</div>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('admin/ajouter-utilisateur'));
$form->setAttribute('method', 'post');
$form->setAttribute('class','form-horizontal no-submit');
$form->get('submit')->setLabel('Valider')->setAttribute('class','btn btn-primary');
echo $this->form()->openTag($form); ?>

    <fieldset>
        <div class="control-group">
        	<label class="control-label">
            <?php echo $this->formLabel($form->get('username')) ?>
            </label>
            <div class="controls">
            <?php echo $this->formInput($form->get('username')) ?>
            <?php echo $this->formElementErrors($form->get('username')) ?>
            </div>
        </div>
        <div class="control-group">
        	<label class="control-label">
            <?php echo $this->formLabel($form->get('displayName')) ?>
            </label>
            <div class="controls">
            <?php echo $this->formInput($form->get('displayName')) ?>
            <?php echo $this->formElementErrors($form->get('displayName')) ?>
            </div>
        </div>
        <div class="control-group">
        	<label class="control-label">
            <?php echo $this->formLabel($form->get('email')) ?>
            </label>
            <div class="controls">
            <?php echo $this->formInput($form->get('email')) ?>
            <?php echo $this->formElementErrors($form->get('email')) ?>
            </div>
        </div>
        <div class="form-actions">
            <?php echo $this->formButton($form->get('submit')) ?>
            <a href="<?php echo $this->url('admin/gestion-users') ?>" role="button" class="btn"> Annuler </a>
        </div>
    </fieldset>
<?php echo $this->form()->closeTag() ?>

