<?php
$title = 'Gestion des utilisateurs';
$this->headTitle($title);
?>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css'); ?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>



<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div>
                <table class="table table-striped table-bordered" id="data">
                    <thead>
                        <tr>
                            <th>Login</th>
                            <th>Nom / Prenom</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="5">En cours de téléchargement</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js') ;?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/dataTables.js') ;?>




<script type="text/javascript">

    var URL = '<?php echo $this->url("admin/gestion-users"); ?>';
    ResultSet.paginate(
		URL, 
		function(){ 
			console.info('Callback executed'); 
		}, 
		{
			"fnDrawCallback": function () {
				$('.status').editable({
					source: [
                    <?php foreach ($roles as $role) : ?>
								{value: <?php echo $role->getId();?>, text: '<?php echo $role->getRoleId();?>'},
                    <?php endforeach; ?>
							]
				});

                $('.text').editable({ });

                $(".SupprimerUser").click(function(event){
                    if(window.confirm("Êtes-vous sûr de vouloir supprimer définitivement l'utilisateur : "+$(this).attr('data-value')+" ?")){
                        $.post( 
                            $(this).attr('data-url'),
                            { name: "supprimer" },
                            function(data) {
                                $("#data").dataTable().fnDraw();
                            });

                    } else {
                        return false;
                    }

                    
                });
			},
            "aoColumns": [
                              null,
                              null,
                              null,
                              { "bSortable": false  },
                              { "bSortable": false  },
                            ],
		}
	);
</script>
