<?php echo $this->doctype(); ?>

<?php
$title = 'Gestion des utilisateurs';
$this->headTitle($title);
?>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <small>Subtext for header</small></h1>
</div>



<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div>
                <table class="table table-striped table-bordered" id="data">
                    <thead>
                        <tr>
                            <th class="span1">Id</th>
                            <th>Login</th>
                            <th>Nom / Prenom</th>
                            <th>Email</th>
                            <th class="span4">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="5">En cours de téléchargement</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js') ;?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/dataTables.js') ;?>



<script>
$(function(){
	
	});
</script>



<script type="text/javascript">
    var URL = '<?php echo $this->url("admin/gestion-users"); ?>';
    ResultSet.paginate(URL);
</script>
