<?php
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-wysihtml5.css');

$title = 'Modifier la page d\'accueil';
$this->headTitle($title);
?>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide : modifier la page d'accueil</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Le contenu de la page d'accueil est modulable, en tant qu'administrateur de l'application vous pouvez ici modifier ce contenu
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> 
    <small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
</div>

<div class="container">

	<form method="post" action="<?php echo $this->url('admin/editAccueil') ?>" class="form-horizontal span11">
		<div class="well">
			<input 	type="textarea"
					class="wysihtml5-textarea input-block-level"
					style="height: 300px"
					placeholder="Entrez le contenu de la page d'accueil"
					value="<?php echo str_replace('"', "'", $this->page->texte); ?>"
					name="wysiwyg"
			/>
		</div>

		<div class="form-actions">
        	<button type="submit" role="submit" class="btn btn-primary"> Valider </button>
        	<a href="<?php echo $this->url('home'); ?>" role="button" class="btn"> Annuler </a>
    	</div>

	</form>

</div>

<?php $this->inlineScript()->captureStart() ?>

	$(function () {
		$('.wysihtml5-textarea').wysihtml5({image:false, locale: "fr-FR"}); 
    });
    
<?php $this->inlineScript()->captureEnd() ?>

<?php 
	$this->headScript()->appendFile($this->basePath() . '/js/wysihtml5-0.3.0.min.js') ;
	$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-wysihtml5.js') ; 
	$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-wysihtml5.fr-FR.js') ;
?>