<?php
// module/Album/view/album/album/index.phtml:

$title = 'Admin';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div>
                <table class="table table-striped table-bordered" id="data">
                    <thead>
                        <tr>
                            <th class="span1">Id</th>
                            <th>Login</th>
                            <th>Nom / Prenom</th>
                            <th>Email</th>
                            <th class="span4">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="4">En cours de téléchargement</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script>
    var URL = '<?php echo $this->serverUrl() . "/admin"; ?>';
    ResultSet.paginate(URL);
</script>