<?php
$title = 'Consultation des logs';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
?>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Cette page vous permet de consulter les actions des utilisateurs.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> 
    <small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div>
                <table class="table table-striped table-bordered data">
                    <thead>
                        <tr>
                            <th>Action</th>
                            <th>Date</th>
                            <th>Objet</th>
                            <th>Utilisateur</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="5">En cours de téléchargement</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="confirmDiv" >
</div> 

<?php $this->inlineScript()->captureStart(); ?>
	var table;
	$(function() {
	
	    table = ResultSet.paginate(
	    	$('.data'),
			{
				"aoColumns": [
		           	           	null,
		           	           	null, 
		           	        	null,
		                     	null
	           	           	 ],
	           	"iColumns": 5,
	           	"bAutoWidth": false,
				"bSortClasses":false,
	           	"bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url("admin/logs"); ?>"
			}
		);

	});
<?php
$this->inlineScript()->captureEnd();

$this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/ResultSet.js');
?>
