<?php
$title = 'Consultation des logs';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> 
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div>
                <table class="table table-striped table-bordered data">
                    <thead>
                        <tr>
                            <th>Action</th>
                            <th>Date</th>
                            <th>Objet</th>
                            <th>Id Objet</th>
                            <th>Utilisateur</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="5">En cours de téléchargement</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="confirmDiv" >
</div> 

<?php $this->inlineScript()->captureStart(); ?>
	var table;
	$(function() {
	
	    table = ResultSet.paginate(
	    	$('.data'),
			{
				"aoColumns": [
		           	           	null,
		           	           	null, 
		           	        	null,
		           	        	null,
		                     	null
	           	           	 ],
	           	"iColumns": 5,
	           	"bAutoWidth": false,
				"bSortClasses":false,
	           	"bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url("admin/logs"); ?>"
			}
		);

	});
<?php
$this->inlineScript()->captureEnd();

$this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/ResultSet.js');
?>
