<?php
$title = 'Gestion des champs select';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/css/select2.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
?>

<div class="messageEditUsers"></div>
<ul class="breadcrumb">
	<li><a href="<?php echo $this->url('page') ?>">Accueil</a> <span class="divider">/</span></li>
    <li class="active"> Administration <span class="divider">/</span></li>
    <li class="active"> Gestion des champs select </li>
</ul>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Cette page vous permet de modifier les champs select.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>


<div class="page-header row-fluid">
    <div class="span9">
        <h1><?php echo $this->escapeHtml($title); ?> 
        <small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
    </div>
    <a class="ajouterSelect btn btn-primary span3" href="#ajouterSelectModal" data-toggle="modal"><i class="icon-plus"></i> Ajouter un select</a>
    <a class="recharger btn btn-warning span3" href="" ><i class="icon-refresh"></i> Rafraichire le tableau </a>
</div>


<!-- AjouterSelect Modal -->
<div id="ajouterSelectModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Ajouter un Select</h3>
    </div>
    <div class="modal-body">
    <div class="form-horizontal">
        <div class="control-group">
            <label class="control-label" for="nom">Label du select</label>
            <div class="controls">
                <input type="text" name="labelSelect" placeholder="Label" value="">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="nom">Description</label>
            <div class="controls">
                <textarea name="descriptionSelect" placeholder="Description" class=""></textarea>
            </div>
        </div>
    </div>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-primary ajouterSelectSubmit">Créer</a>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div>
                <table class="table table-striped table-bordered data">
                    <thead>
                        <tr>
                            <th>Label</th>
                            <th>Description</th>
                            <th>Apercu</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="4">En cours de téléchargement</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="confirmDiv" >
</div> 
<div id="modalDiv"></div>


<?php $this->inlineScript()->captureStart(); ?>
	var table;
	$(function() {
	
	    table = ResultSet.paginate(
	    	$('.data'),
			{
				"aaSorting": [ [1,'desc'] ],
				"aoColumns": [
		           	           	null,
		           	           	null, 
                                { "bSortable": false  },
		           	        	{ "bSortable": false  },
	           	           	 ],
	           	"iColumns": 4,
	           	"bAutoWidth": false,
				"bSortClasses":false,
	           	"bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url("champSelect"); ?>",
                "fnDrawCallback": function () {
    
                    $('[data-toggle="popover"]').popover({placement:'top', trigger:'hover'}); 
    
                    $('.text').editable({ 
                        mode: 'inline',
                        emptytext: "Vide",
                        success: function(e) {
                            var resp = jQuery.parseJSON(e);
                                                            
                            if(resp.success === true){
                                //location.reload();
                                $('.messageEditUsers').showInfos(resp.message, "success");
                            } else {
                                //location.reload();
                                $('.messageEditUsers').showInfos(resp.error, "error");
                            }
                        }
                     });

                    $(".select").select2();

                    $(document).on( 'click', '.modifierValue', function(e){
                        var dataURL = $(this).attr('data-url');
                        $.ajax({
                            url: dataURL,
                            type: "POST",
                            data:{ name:'voirListe' }, 
                            success:function(response){
                    
                                if(response == 'true') {
                                    location.reload();
                                } else {
                                    $('#modalDiv').html('<div id="SelectValuesModal" class="modal">' + response + '</div>').modal();
                                     $('.text').editable({ 
                                        mode: 'inline',
                                        emptytext: "Vide",
                                    });
                                }
                    
                            },
                            error: function(response){
                                alert('Impossible d\'ajouter des champ');
                            }
                        });
                    });
                     
                }
			}
		);
        // ajouter un select
        $(document).on( 'click', '.ajouterSelectSubmit', function(e){
            var label = $('input[name="labelSelect"]');
            var description = $('textarea[name="descriptionSelect"]');
            $.ajax({
                url: "<?php echo $this->url("champSelect/ajouter");?>",
                type: "POST",
                data:{ 
                name:'ajouterSelect', 
                labelSelect: label.val(),
                descriptionSelect: description.val()}
            }).done(function(e){
                 table.fnDraw(); 
                var resp = jQuery.parseJSON(e);
                $('.messageEditUsers').showInfos(resp.message, resp.type);
                $('#ajouterSelectModal').modal('hide');
                label.val('');
                description.val('');
                
            });
        });
        $(document).on( 'click', '.supprimerSelect', function(e){
            var dataURL = $(this).attr('data-url');
            $.ajax({
                url: dataURL,
                type: "POST",
                data:{ name:'supprimerSelect'}
            }).done(function(e){
                table.fnDraw();
                var resp = jQuery.parseJSON(e);
                $('.messageEditUsers').showInfos(resp.message, resp.type);
            });
        });
        // supprimer une valeur d'un select 
        $(document).on( 'click', '.SupprimerValue', function(e){
            var dataURL = $(this).attr('data-url');
            var thisTR = $(this).parents('tr');
            $.ajax({
                url: dataURL,
                type: "POST",
                data:{ name:'supprimerValue' }
            }).done(function(e){
                var resp = jQuery.parseJSON(e);
                $('#response').html('<div class="alert alert-'+resp.type+'"><button type="button" class="close" data-dismiss="alert">&times;</button>'+resp.message+'</div>');
                if(resp.type == 'success'){
                    thisTR.remove();
                }
            });
        });
                                    // on recharge le tableu quand on ferme la modal SelectValuesModal
                                    $('#modalDiv').on('hidden', function () {
                                        table.fnDraw();
                                    })
        // ajouter une valeur a un select
        $(document).on( 'click', '.AjouterValue', function(e){
            var dataURL = $(this).attr('data-url');
            var thisTable = $(this).parents('table');
            var dataValue = $('#ajouterValueInput');
            $.ajax({
                url: dataURL,
                type: "POST",
                data:{ name:'ajouterValue', value:dataValue.val() }
            }).done(function(e){
                var resp = jQuery.parseJSON(e);
                $('#response').html('<div class="alert alert-'+resp.type+'"><button type="button" class="close" data-dismiss="alert">&times;</button>'+resp.message+'</div>');
                if(resp.type == 'success'){
                    $('#ListeValue').append('<tr id="eee">'+resp.addTable+'</tr>');

                    $('.modal-body').animate({  
                        scrollTop:$('#'+resp.id).offset().top  
                    }, 'slow');  

                    dataValue.val('');

                    $('.text').editable({ 
                        mode: 'inline',
                        emptytext: "Vide",
                    });
                }

            });
        });
        

	});
<?php
$this->inlineScript()->captureEnd();

$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js');
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/ResultSet.js');
$this->headScript()->appendFile($this->basePath() . '/js/select2.js');
$this->headScript()->appendFile($this->basePath() . '/js/locales/select2_locale_fr.js') ;
?>
