<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modifier Value</h3>
</div>
<div class="modal-body">

    <table class="table table-hover">
        <tr>
            <th>Liste des valeurs</th>
            <th>Action</th>
        </tr>
        <?php
        foreach ($select->select_values as $select_value) {
            echo '<tr><td>'.$select_value->text."</td>";

            echo '<td>
            <a class="btn btn-danger" href="#">
                <i class="icon-trash icon-large"></i> 
            </a>
                </td>';

            echo '</tr>';
        }
        ?>
    </table>

</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
</div>