<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modifier Value</h3>
</div>
<div class="modal-body">
<div id="response"></div>
    <table id="ListeValue" class="table table-hover">
        <tr>
            <th>Liste des valeurs</th>
            <th>Action</th>
        </tr>
        <?php
        foreach ($select->select_values as $select_value) {
            echo '<tr><td id="'.$select_value->id.'"><span id="label" 
                        class="text CursorPointer" 
                        data-url="'.$this->url("champSelect/modifierValueAjax", array("id" => $select->id, "idValue" => $select_value->id)).'" 
                        data-value="'.$this->escapeHtml($select_value->text).'" 
                        data-name="modifierTexte" 
                        data-placement="right" 
                        data-type="text" 
                        data-pk="1">'.$this->escapeHtml($select_value->text).'
                    </span></td>';



            echo '<td>
            <a class="btn btn-danger SupprimerValue" 
            data-url="'.$this->url("champSelect/modifierValueAjax", array("id" => $select->id, "idValue" => $select_value->id)).'"
            href="#">
                <i class="icon-trash "></i> 
            </a>
                </td>';



            echo '</tr>';


        }

        ?>
    </table>

</div>
<div class="modal-footer">
    <div class="input-append pull-left" >
        <input id="ajouterValueInput" type="text" name="ajouterValueInput">
        <button class="btn AjouterValue" 
            data-url="<?php echo $this->url("champSelect/modifierValueAjax", array("id" => $select->id));?>"
            href="#">
                <i class="icon-plus "></i> 
        </button>
    </div>
    
    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
</div>