<?php 

$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-wysihtml5.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/pillbox.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/css/datepicker.css');

$title = $scene->titre;
$this->headTitle($title);
?>

<div class="page-header row-fluid">
	<div class="span9">
		<h1>
		Modification d'une scène : <br/>
		<span class="edit CursorPointer" data-inputclass="span12" data-name="titre" data-type="text" data-pk="1" data-url="<?php echo $this->url("scene/editScene",array('id'=>$scene->id)) ?>"><?php echo $this->escapeHtml($title); ?></span> 
		</h1>
	</div>
	
	<a href="<?php echo $this->url('scene/voirScene',array('id' => $scene->id)) ?>" class="btn btn-primary span3">
		<i class="icon-reply"> </i>
        Retour à la fiche de cette scène
    </a>
	
</div>

<!--Confirm Modal -->
<div id="confirmModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Confirmation : suppression d'une scène</h3>
    </div>
    <div class="modal-body">
    	Êtes-vous sur de vouloir supprimer la scène "<?php echo $this->escapeHtml($scene->titre); ?>" ?
    </div>
    <div class="modal-footer">
	    <a href="<?php echo $this->url('scene/removeScene',
            array('id' => $scene->id)) ?>" class="btn btn-primary">Supprimer</a>
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<!-- Transitions autour de cette scène -->
<div class="row-fluid">

	<div class="span6">
		<h5>Transitions secondaires entrantes</h5>
		<table class="table">
			<?php if ($transitions_secondaires == null) :?>
				Aucune tansition secondaire ne mène à cette scène.
			<?php else: ?>
				<?php foreach ($transitions_secondaires as $transition) : ?>
					<tr><td>
						<ul class="nav nav-list">
						<li>
							<a href="<?php echo $this->url('scene/voirScene', array('id' => $transition->scene_origine->id)) ?>"> 
								<i class="icon-file-alt"></i>  
								<em> <?php echo $this->escapeHtml($transition->scene_origine->titre); ?> </em>
								<i class="icon-arrow-right"></i> 
							</a>
							[<?php echo $this->escapeHtml($transition->semantique->semantique); ?>]
							"<?php echo $this->escapeHtml($transition->narration); ?>"
						</li>
						</ul>
					</td></tr>
				<?php endforeach; ?>
			<?php endif;?>
		</table>
	</div>
	
	<div class="span6">
		<h5>Transitions secondaires sortantes</h5>
		<table class="table">
			<?php if ($scene->transitions_secondaires == null 
					|| $scene->transitions_secondaires->count() == 0) :?>
				Aucune tansition secondaire ne part de cette scène.
			<?php else: ?>
				<?php foreach ($scene->transitions_secondaires as $transition) : ?>
					<tr><td>
						<ul class="nav nav-list">
						<li>
							[<?php echo $this->escapeHtml($transition->semantique->semantique); ?>]
							"<?php echo $this->escapeHtml($transition->narration); ?>"
							<a href="<?php echo $this->url('scene/voirScene', array('id' => $transition->scene_destination->id)) ?>"> 
								<i class="icon-arrow-right"></i> 
								<i class="icon-file-alt"></i> 
								<em> <?php echo $this->escapeHtml($transition->scene_destination->titre); ?> </em>
							</a>
						</li>
						</ul>
					</td></tr>
				<?php endforeach; ?>
			<?php endif;?>
       	</table>
	</div>
	
</div>

<hr>

<div class="row-fluid">

	<div class="span6 well">
		<form id="textarea">
			<textarea class="textarea-wysihtml5 input-block-level" data-name="description" rows="10" data-url="<?php echo $this->url("scene/editScene",array('id'=>$scene->id)) ?>"><?php echo $scene->narration;?></textarea>
			<button type="button" class="textarea-submit btn btn-primary editable-submit"><i class="icon-ok icon-white"></i> Enregistrer</button>
		</form>
		<div id="textarea-return"></div>
	</div>
	
	<div class="span6 well">
		<h2>À voir dans cette scène</h2>
		<hr/>
		<h4> Eléments déjà présents </h4>
		<?php if ($scene->elements->count() == 0): ?>
				Aucun élément de la collection n'est lié à cette scène.
		<?php endif; ?>
		<?php if ($scene->elements != null) : ?>
			<table class="table">
			<?php foreach($scene->elements as $element) : ?>
				<?php if($element instanceof Collection\Entity\Artefact) : ?>
					<tr>
					<td>
						<a href="<?php echo $this->url('artefact/voirArtefact',array('id' => $element->id))?>"> 
						<i class="icon-tag"></i> <?php echo $this->escapeHtml($element->titre); ?>
					 	</a>
					</td>
					<td>
						<a href="#" data-value=" <?php echo $this->escapeHtml($element->titre); ?>" 
							class="deleteElement"
							data-url="<?php echo $this->url('scene/deleteElement', array('idScene' => $scene->id, 'idElement' => $element->id)); ?>">
						<i class="icon-trash"></i>
						</a>
					</td>
					<tr>
				<?php elseif($element instanceof Collection\Entity\Media) : ?>
					<tr>
					<td>
						<a href="<?php echo $this->url('media/voirMedia',array('id' => $element->id))?>"> 
						<i class="icon-picture"></i> <?php echo $this->escapeHtml($element->titre); ?>
					 	</a>
					</td>
					<td>
						<a href="#" data-value=" <?php echo $this->escapeHtml($element->titre); ?>" 
							class="deleteElement"
							data-url="<?php echo $this->url('scene/deleteElement', array('idScene' => $scene->id, 'idElement' => $element->id)); ?>">
						<i class="icon-trash"></i>
						</a>
					</td>
					<tr>
				<?php endif; ?>
			<?php endforeach ;?>
			</table>
		<?php else : ?>
			<p> Aucun élément de la collection n'est présent cette scène. </p>
		<?php endif; ?>
		
		<h4>Ajouter des éléments à la scène </h4>
		<div class="well">
			<?php echo $this->DatatableWidget( 'scene' ); ?> 
		</div>
	</div>
</div>


<div id="confirmDiv" >
</div>

<?php $this->inlineScript()->captureStart(); ?>
	
	var element = {'id' : <?php echo $scene->id; ?>, 'titre' : '<?php echo $this->escapeHtml($scene->titre); ?>' };
	
	$(function () {

		$(".deleteElement").click(function(event){
        	var dataURL = $(this).attr('data-url');
            var dataValue = $(this).attr('data-value');
            $('#confirmDiv').confirmModal({
                heading:'Confirmation',
                body:"Êtes-vous sûr de vouloir supprimer définitivement la liaison entre cette scène et <i>" + dataValue + " </i>?",
                callback: function() {
                     $.post(
                     	dataURL,
                        { name: "supprimer" },
                        function(response) {
		                	document.location.reload();
		            	}
                    );
                }
          	});
      	});

		$('.textarea-wysihtml5').wysihtml5({
			locale: "fr-FR",
			image: false,
			stylesheets: ["<?php echo $this->basePath() . '/css/bootstrap.css';?>"],
			"events": {
				"load": function() { 
					$(editor.composer.iframe).wysihtml5_size_matters();
				}
			}
		});

		$("#textarea").on("click",".textarea-submit", function(e){
		DataValue = $('.textarea-wysihtml5').val();
			$.ajax({
				url: "<?php echo $this->url("scene/editScene",array('id'=>$scene->id)) ?>",
				type: "POST",
				data:{ name:'description', value: DataValue }, 
			}).done(function(){
				$('#textarea-return').html('<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>Enregistrement réussi</div>')
			});
		});

	    $(".file-input-form").on('submit', function (e){
	    	e.preventDefault();
	    	$(this).ajaxSubmit({
				data: {name: 'data'},
				success: function(data) { document.location.reload(); }
            });
	    });

		$('.picker').editable({
			mode: 'popup',
			placement: 'top',
			format: 'yyyy-mm-dd',
			viewformat: 'dd-mm-yyyy',
			 datepicker: {
				language:'fr',
			}
		});
		
		$('.edit').editable({
			mode: 'inline',
			emptytext: 'Vide'
		});
		
    });
    
<?php 
$this->inlineScript()->captureEnd();

$this->headScript()->appendFile($this->basePath() . '/js/jquery.form.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/ResultSet.js');
$this->headScript()->appendFile($this->basePath() . '/js/pillbox.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/wysihtml5-0.3.0.min.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-wysihtml5.js') ; 
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-wysihtml5.fr-FR.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/editable.wysihtml5.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/jquery.wysihtml5_size_matters.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap.file-input.js');
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js');

?>
