<?php 

$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-wysihtml5.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/pillbox.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/css/datepicker.css');

$title = $scene->titre;
$this->headTitle($title);
?>

<!-- En tête -->
<div class="page-header">
	<div class="row-fluid">
		<div class="span9">
			<h1>
			Modification d'une scène : <br/>
			<span class="edit CursorPointer" data-inputclass="span12" data-name="titre" data-type="text" data-pk="1" data-url="<?php echo $this->url("scene/editScene",array('id'=>$scene->id)) ?>"><?php echo $this->escapeHtml($title); ?></span> 
			</h1>
		</div>
		<div class="span3">
		<a href="<?php echo $this->url('parcours/voir', array('id' => $scene->sous_parcours->parcours->id)) ?>" 
			class="btn btn-primary btn-block"> 
			<i class="icon-reply"></i> Retour au parcours <em><?php echo $scene->sous_parcours->parcours->titre; ?></em>
		</a>
		<a href="<?php echo $this->url('scene/voirScene',array('id' => $scene->id)) ?>" 
			class="btn btn-primary btn-block">
			<i class="icon-reply"> </i>
	        Retour à la fiche de la scène
	    </a>
	    </div>
    </div>
    <a href="<?php echo $this->url('parcours/voirParcourHalviz',array('id' => $scene->sous_parcours->parcours->id)) ?>"
    	target="_blank"
    	class="btn btn-warning">
    	<i class="icon-code-fork"></i> Graphe du parcours
	</a>
</div>

<!-- Transitions autour de cette scène -->
<div class="row-fluid">

	<!-- Transitions entrantes -->
	<div class="span6">
		<h3>Transitions secondaires entrantes</h3>
		<table class="table">
			<?php if ($transitions_secondaires_entrantes == null) :?>
				Aucune tansition secondaire ne mène à cette scène.
			<?php else: ?>
				<tr>
					<th>Scène précédente</th>
					<th>Transition</th>
					<th></th>
				</tr>
				<?php foreach ($transitions_secondaires_entrantes as $transition) : ?>
					<tr>
					<td>
						<a href="<?php echo $this->url('scene/editScene', array('id' => $transition->scene_origine->id)) ?>"> 
							<i class="icon-file-alt"></i>  
							<em> <?php echo $this->escapeHtml($transition->scene_origine->titre); ?> </em>
							<i class="icon-arrow-right"></i>  
						</a>
					</td>
					<td>
						[<?php echo ($transition->semantique) ? $transition->semantique->semantique : 'Sémantique inconnue' ; ?>
						<a href="#" 
			            	class="selectSemantiques" 
			            	data-value="<?php echo ($transition->semantique) ? $transition->semantique->id : 'null' ; ?>"
			                data-url="<?php echo $this->url('parcours/modifierTransition', array('id' => $transition->id)) ?>">
			                <i class="icon-pencil"></i>  
			            </a>]
			            <span class="edit CursorPointer"
				        	data-url="<?php echo $this->url("parcours/modifierTransition", array("id" => $transition->id)); ?>"
				            data-name="narration" 
				            data-type="text" 
				            data-pk="1"><?php echo $this->escapeHtml($transition->narration); ?>
				        </span>
					</td>
					<td>
						<a href="#" 
							data-value=" <?php echo $this->escapeHtml($transition->narration); ?>" 
							class="deleteTransition"
							data-url="<?php echo $this->url('parcours/supprimerTransitionSec', array('id' => $transition->id)); ?>">
						<i class="icon-trash"></i>
						</a>
					</td>
					</tr>
				<?php endforeach; ?>
			<?php endif;?>
			<td>
       			<div class="input-append">
			       	<select id="selectSceneOrigine">
			       		<?php foreach ($scenes_parcours as $scene_parcours) :?>
						<option value="<?php echo $scene_parcours->id; ?>">
							<?php  echo $scene_parcours->titre; ?>
						</option>
						<?php endforeach; ?>
					</select>
					<button class="btn btn-primary ajouterTransitionSecEntrante" type="submit">
						<i class="icon-plus"></i>
					</button>
			 	</div>
			</td>
			<td>
				... Ajouter une transition secondaire entrante depuis
			</td>
		</table>
	</div>
	
	<!-- Tranitions sortantes -->
	<div class="span6">
		<h3>Transitions secondaires sortantes</h3>
		<table class="table">
			<?php if ($scene->transitions_secondaires == null 
					|| $scene->transitions_secondaires->count() == 0) :?>
				Aucune tansition secondaire ne part de cette scène.
			<?php else: ?>
				<tr>
					<th>Transition</th>
					<th>Scène suivante</th>
					<th></th>
				</tr>
				<?php foreach ($scene->transitions_secondaires as $transition) : ?>
					<tr>
					<td>
						[<?php echo ($transition->semantique) ? $transition->semantique->semantique : 'Sémantique inconnue' ; ?>
						<a href="#" 
			            	class="selectSemantiques" 
			            	data-value="<?php echo ($transition->semantique) ? $transition->semantique->id : 'null' ; ?>"
			                data-url="<?php echo $this->url('parcours/modifierTransition', array('id' => $transition->id)) ?>">
			                <i class="icon-pencil"></i> 
			            </a>]
			            <span class="edit CursorPointer"
				        	data-url="<?php echo $this->url("parcours/modifierTransition", array("id" => $transition->id)); ?>"
				            data-name="narration" 
				            data-type="text" 
				            data-pk="1"><?php echo $this->escapeHtml($transition->narration); ?>
				        </span>
					</td>
			        <td>
						<a href="<?php echo $this->url('scene/editScene', array('id' => $transition->scene_destination->id)) ?>"> 
							<i class="icon-arrow-right"></i>  
							<i class="icon-file-alt"></i>  
							<em> <?php echo $this->escapeHtml($transition->scene_destination->titre); ?> </em>
						</a>
					</td>
					<td>
						<a href="#" 
							data-value=" <?php echo $this->escapeHtml($transition->narration); ?>" 
							class="deleteTransition"
							data-url="<?php echo $this->url('parcours/supprimerTransitionSec', array('id' => $transition->id)); ?>">
						<i class="icon-trash"></i>
						</a>
					</td>
					</tr>
				<?php endforeach; ?>
			<?php endif;?>
			<tr>
				<td>
					Ajouter une transition sortante vers...
				</td>
				<td>
       			    <div class="input-append">
			       		<select id="selectSceneDestination">
			       			<option value="0">
								-- Créer une nouvelle scène comme destination --
							</option>
			       			<?php foreach ($scenes_parcours as $scene_parcours) :?>
							<option value="<?php echo $scene_parcours->id; ?>">
								<?php  echo $scene_parcours->titre; ?>
							</option>
							<?php endforeach; ?>
						</select>
						<button class="btn btn-primary ajouterTransitionSecSortante" type="submit">
							<i class="icon-plus"></i>
						</button>
				 	</div>
				</td>
			</tr>
       	</table>
	</div>
	
</div>

<hr>

<div class="row-fluid">

	<div class="span6 well">
		<h3>Narration</h3>
		<hr>
		<form id="textarea">
			<textarea class="textarea-wysihtml5 input-block-level" data-name="description" rows="10" data-url="<?php echo $this->url("scene/editScene",array('id'=>$scene->id)) ?>"><?php echo $scene->narration;?></textarea>
			<button type="button" class="textarea-submit btn btn-primary editable-submit"><i class="icon-ok icon-white"></i> Enregistrer</button>
		</form>
		<div id="textarea-return"></div>
	</div>
	
	<div class="span6 well">
		<h3>À voir dans cette scène</h3>
		<hr/>
		<h4> Eléments déjà présents </h4>
		<?php if ($scene->elements->count() == 0): ?>
				Aucun élément de la collection n'est lié à cette scène.
		<?php endif; ?>
		<?php if ($scene->elements != null) : ?>
			<table class="table">
			<?php foreach($scene->elements as $element) : ?>
				<?php if($element instanceof Collection\Entity\Artefact) : ?>
					<tr>
					<td>
						<a href="<?php echo $this->url('artefact/voirArtefact',array('id' => $element->id))?>"> 
						<i class="icon-tag"></i> <?php echo $this->escapeHtml($element->titre); ?>
					 	</a>
					</td>
					<td>
						<a href="#" data-value=" <?php echo $this->escapeHtml($element->titre); ?>" 
							class="deleteElement"
							data-url="<?php echo $this->url('scene/deleteElement', array('idScene' => $scene->id, 'idElement' => $element->id)); ?>">
						<i class="icon-trash"></i>
						</a>
					</td>
					<tr>
				<?php elseif($element instanceof Collection\Entity\Media) : ?>
					<tr>
					<td>
						<a href="<?php echo $this->url('media/voirMedia',array('id' => $element->id))?>"> 
						<i class="icon-picture"></i> <?php echo $this->escapeHtml($element->titre); ?>
					 	</a>
					</td>
					<td>
						<a href="#" data-value=" <?php echo $this->escapeHtml($element->titre); ?>" 
							class="deleteElement"
							data-url="<?php echo $this->url('scene/deleteElement', array('idScene' => $scene->id, 'idElement' => $element->id)); ?>">
						<i class="icon-trash"></i>
						</a>
					</td>
					<tr>
				<?php endif; ?>
			<?php endforeach ;?>
			</table>
		<?php else : ?>
			<p> Aucun élément de la collection n'est présent cette scène. </p>
		<?php endif; ?>
		
		<h4>Ajouter des éléments à la scène </h4>
		<div class="well">
			<?php echo $this->DatatableWidget( 'scene' ); ?> 
		</div>
	</div>
</div>


<div id="confirmDiv" >
</div>

<?php $this->inlineScript()->captureStart(); ?>
	
	var element = {'id' : <?php echo $scene->id; ?>, 'titre' : '<?php echo $this->escapeHtml($scene->titre); ?>' };
	
	$(function () {

		$(".deleteElement").click(function(event){
        	var dataURL = $(this).attr('data-url');
            var dataValue = $(this).attr('data-value');
            $('#confirmDiv').confirmModal({
                heading:'Confirmation',
                body:"Êtes-vous sûr de vouloir supprimer définitivement la liaison entre cette scène et <i>" + dataValue + " </i>?",
                callback: function() {
                     $.post(
                     	dataURL,
                        { name: "supprimer" },
                        function(response) {
		                	document.location.reload();
		            	}
                    );
                }
          	});
      	});
      	
      	$(".deleteTransition").click(function(event){
        	var dataURL = $(this).attr('data-url');
            var dataValue = $(this).attr('data-value');
            $('#confirmDiv').confirmModal({
                heading:'Confirmation',
                body:"Êtes-vous sûr de vouloir supprimer définitivement la transition <i>" + dataValue + " </i>?",
                callback: function() {
                     $.post(
                     	dataURL,
                        { name: "supprimer" },
                        function(response) {
		                	document.location.reload();
		            	}
                    );
                }
          	});
      	});
      	
      	$(".ajouterTransitionSecSortante").click(function(e){
      		selectElmt = document.getElementById('selectSceneDestination');
      		idSceneDest = selectElmt.options[selectElmt.selectedIndex].value;
            $.ajax({
				url: "<?php echo $this->url('parcours/ajouterTransitionSec'); ?>",
				type: "POST",
				data:{
					idSceneOrigine: <?php echo $scene->id;?>,
					idSceneDestination: idSceneDest
					}
			}).done(function(){
				document.location.reload()
			});
      	});

      	$(".ajouterTransitionSecEntrante").click(function(e){
      		selectElmt = document.getElementById('selectSceneOrigine');
      		idSceneOrigine = selectElmt.options[selectElmt.selectedIndex].value;
            $.ajax({
				url: "<?php echo $this->url('parcours/ajouterTransitionSec'); ?>",
				type: "POST",
				data:{
					idSceneOrigine: idSceneOrigine,
					idSceneDestination: <?php echo $scene->id;?>
					}
			}).done(function(){
				document.location.reload()
			});
      	});
      	
		$('.textarea-wysihtml5').wysihtml5({
			locale: "fr-FR",
			image: false,
			stylesheets: ["<?php echo $this->basePath() . '/css/bootstrap.css';?>"],
			"events": {
				"load": function() { 
					$(editor.composer.iframe).wysihtml5_size_matters();
				}
			}
		});

		$("#textarea").on("click",".textarea-submit", function(e){
		DataValue = $('.textarea-wysihtml5').val();
			$.ajax({
				url: "<?php echo $this->url("scene/editScene",array('id'=>$scene->id)) ?>",
				type: "POST",
				data:{ name:'description', value: DataValue }, 
			}).done(function(){
				$('#textarea-return').html('<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>Enregistrement réussi</div>')
			});
		});

	    $(".file-input-form").on('submit', function (e){
	    	e.preventDefault();
	    	$(this).ajaxSubmit({
				data: {name: 'data'},
				success: function(data) { document.location.reload(); }
            });
	    });

		$('.picker').editable({
			mode: 'popup',
			placement: 'top',
			format: 'yyyy-mm-dd',
			viewformat: 'dd-mm-yyyy',
			 datepicker: {
				language:'fr',
			}
		});
		
		$('.edit').editable({
			mode: 'inline',
			emptytext: 'Vide'
		});
		
		// on affiche le modal avec les semantiques
        $(".selectSemantiques").on("click", function(e){
            var dataURL = $(this).attr('data-url');
            var dataValue = $(this).attr('data-value');

            var body = new String('<form id="semantiqueTransitions" action="'+dataURL+'"><dl><?php foreach ($SemantiqueTransitions as $semantique) { ?><label class="radio"><dt><input type="radio" name="SemantiqueTransitions" id="SemantiqueTransitions<?php echo $this->escapeHtml($semantique->id) ;?>" value="<?php echo $this->escapeHtml($semantique->id) ;?>" ><?php echo $this->escapeHtml($semantique->semantique) ;?></dt><dd><?php echo $this->escapeHtml($semantique->description) ;?></dd></label><?php } ?></dl></form>');
            body = body.replace('id="SemantiqueTransitions'+dataValue+'"', 'id="SemantiqueTransitions'+dataValue+'" checked="checked"' );
            $('#confirmDiv').confirmModal({
                heading:"Sélectionner le type de Semantique",
                body:body,
                callback: function() {
                    var $form = $('#semantiqueTransitions');
                    var inputVal = $form.find( 'input[name="SemantiqueTransitions"]:checked' ).val();
                    var URL = $form.attr( 'action' );
                     $.post(
                        dataURL,
                        { name: "semantique",value:inputVal },
                        function() {
                        	document.location.reload();
                        }
                    );
                }
            });
            $('#SemantiqueTransitions'+dataValue).prop('checked');
        });
		
    });
    
<?php 
$this->inlineScript()->captureEnd();

$this->headScript()->appendFile($this->basePath() . '/js/jquery.form.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/ResultSet.js');
$this->headScript()->appendFile($this->basePath() . '/js/pillbox.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/wysihtml5-0.3.0.min.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-wysihtml5.js') ; 
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-wysihtml5.fr-FR.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/editable.wysihtml5.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/jquery.wysihtml5_size_matters.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap.file-input.js');
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js');

?>
