<?php 
$title = $scene->titre;
$this->headTitle($title); ?>

<div class="row-fluid">

	<!-- Menu de navigation dasn le parcours -->
	<div class="span4 well">
		<h4> <i class="icon-road"></i> <?php echo $scene->sous_parcours->parcours->titre; ?> </h4>
		<a href="<?php echo $this->url('parcours/voir', array('id' => $scene->sous_parcours->parcours->id)) ?>" 
			class="btn btn-link"> 
			<i class="icon-reply"></i> Retour au parcours 
		</a>
		
		<ul class="nav nav-list">
			<?php 
			$scene_depart = $scene->sous_parcours->scene_depart;
			$transition = $scene_depart->transition_recommandee;
			$class = "";
			if ($scene_depart == $scene) {
				$class = "active";
			}
			?>
			<li class="divider"></li>	
			<li class="<?php echo $class; ?>">
				<a href="<?php echo $this->url('scene/voirScene', array('id' => $scene_depart->id)) ?>">
				<?php echo $scene_depart->titre; ?> 
				</a>
			</li>
			
			<?php while ($transition != null) : ?>
				<?php 
				if ($transition->scene_destination == $scene) {
					$class = "active";
				} else {
					$class = "";
				} ?>
				<li class="<?php echo $class; ?>">
					<table class="muted" border="0">
					<tr>
						<td> <small> <i class="icon-arrow-down"></i> </small> </td>
						<td> <small> <?php echo $transition->narration; ?> </small> </td>
					</tr>
					</table> 
					<a href="<?php echo $this->url('scene/voirScene', array('id' => $transition->scene_destination->id)) ?>">
					<?php echo $transition->scene_destination->titre; ?> 
					</a>
				</li>
				<?php $transition = $transition->scene_destination->transition_recommandee; ?>
			<?php endwhile; ?>
		</ul>
	</div>

	<!-- Fiche de la scène -->
	<div class="span8">
	
		<!-- Titre de la scène -->
		<div class="page-header row-fluid">
			<div class="span8">
			<h1><i class="icon-file-alt"></i> <?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
			</div>
			<?php if ($this->isAllowed('Parcours') === true) :?>
				<span class="btn-group span4 row-fluid">
					<a href="<?php echo $this->url('scene/editScene',array('id' => $scene->id)) ?>" 
						class="btn btn-primary span12">
						<i class="icon-pencil"> </i> Modifier cette scène
					</a>
				</span>
		    <?php endif; ?>
		</div>
		
		<div class="row-fluid">
		
			<!-- Narration de la scène -->
			<div class="span8">
				<p><?php echo $scene->narration;?></p>
			</div>
			
			<!-- Eléments de la collection liés à la scène -->
			<div class="span4 well">
				<h4> A voir dans cette scène </h4>
				<?php if ($scene->elements->count() == 0): ?>
					Aucun élément de la collection n'est lié à cette scène.
				<?php endif; ?>
				<ul class="nav nav-list">
				<?php foreach( ($scene->elements) as $element) : ?>
					<?php if($element instanceof Collection\Entity\Artefact): ?>
						<li>
							<a href="<?php echo $this->url('artefact/voirArtefact',array('id' => $element->id)); ?>">
							<i class="icon-tag"></i>  <?php echo $element->titre; ?> 
							</a>
						</li>
					<?php else : ?>
						<li class="">
							<a href="<?php echo $this->url('media/voirMedia',array('id' => $element->id)); ?>">
							<i class="icon-picture"></i>  <?php echo $element->titre; ?> 
							</a>
						</li>
					<?php endif;  ?>
				<?php endforeach; ?>
				</ul>
			</div>
			
		</div>
		
	</div>
</div>
