
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Ajouter une sémantique</h3>
	</div>
	
	<div class="modal-body">
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>Sémantiques</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>Mark</td>
					<td>Otto</td>
					<td>@mdo</td>
				</tr>
	    	</tbody>
		</table>
	</div>

