<?php
$title = $media->titre;
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-wysihtml5.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/css/datepicker.css');

?>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide : modification d'un média</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Cette page vous permet de modifier les informations d'un média. Tous les champs sont modifiables en cliquant directement dessus.
    	</p>
    	<p>
    	L'onglet 'artefacts liés' permet de gérer les relations mais n'est pas encore implémenté.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header row-fluid">
	<div class="span9">
		<h1>
		Modification d'un média :
		<small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </br>
		<span class="edit CursorPointer" data-inputclass="span12" data-name="titre" data-type="text" data-pk="1" data-url="<?php echo $this->url('media/editMedia',array('id'=>$media->id)) ?>"><?php echo $this->escapeHtml($title); ?></span>
		</h1>
	</div>
	
	<a href="<?php echo $this->url('media/voirMedia',
        	array('id' => $media->id)) ?>" class="btn btn-primary span3"><i class="icon-reply"> </i> Retour à la fiche de ce média</a>
	<a href="#confirmModal" data-toggle="modal" class="btn btn-danger span3"><i class="icon-trash"> </i>  Supprimer ce média</a>
</div>

<!--Confirm Modal -->
<div id="confirmModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Confirmation : suppression d'un média</h3>
    </div>
    <div class="modal-body">
    	Êtes-vous sur de vouloir supprimer le média "<?php echo $this->escapeHtml($media->titre); ?>" ?
    </div>
    <div class="modal-footer">
	    <a href="<?php echo $this->url('media/removeMedia',
            array('id' => $media->id)) ?>" class="btn btn-primary">Supprimer</a>
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="row-fluid">
	<div class="span6 well">
		<form id="textarea">
			<textarea class="textarea-wysihtml5 input-block-level" data-name="description" rows="10" data-url="<?php echo $this->url("media/editMedia",array('id'=>$media->id)) ?>"><?php echo $media->description;?></textarea>
			<button type="button" class="textarea-submit btn btn-primary editable-submit"><i class="icon-ok icon-white"></i> Enregistrer</button>
		</form>
		<div id="textarea-return"></div>
	</div>

	<div class="span6 well">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-info-sign"></i> Information</a></li>
			<li><a href="#tab2" data-toggle="tab"><i class="icon-sitemap"></i> Artefacts liés</a></li>
		</ul>
		<div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
			<div class="tab-pane active" id="tab1">
				<dl>
					<dt>Type de média</dt>
					<dd>
						<?php 
							echo $this->escapeHtml($media->type_element->nom); 
							echo '</br></br>';
						?>
					</dd>
					<?php foreach($datas as $data) :?>
					<dt>
						<?php echo $this->escapeHtml($data->champ->label); ?> 
						<?php if ($data->champ->description != null) : ?>
				        	<a href="#" 
			        			class="description"
			        			rel="popover"
			        			data-content="<?php echo $this->escapeHtml($data->champ->description); ?>"
			        			data-original-title="Description du champ"><i class="icon-question-sign"></i></a>  
			        	<?php endif; ?>
					</dt>
					<dd>
						<?php 
						switch ($data->champ->format) :
							case 'texte':
								echo '<span class="edit CursorPointer" 
											data-name="data" 
											data-type="text" 
											data-pk="'.$data->champ->id.'" 
											data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">
										'.$this->escapeHtml($data->texte).'
									</span>';
								echo '</br></br>';
								break;
							case 'textarea':
								echo '<span class="edit CursorPointer" 
											data-name="data" 
											data-type="textarea" 
											data-pk="'.$data->champ->id.'" 
											data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">
	    								'.$this->escapeHtml($data->textarea).'
    								</span>';
								echo '</br></br>';
								break;

							case 'date':
								if($data->date === null){
									$date = null;
								} else {
									$date = $data->date->format('d-m-Y');
								}
								echo '<span class="picker CursorPointer" 
    										data-name="data" 
    										data-type="date" 
    										data-pk="'.$data->champ->id.'" 
	    									data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">
										'.$date.'
									</span>';
								echo '</br></br>';
								break;
							
							case 'nombre':
								echo '<span class="edit CursorPointer" 
											data-name="data" 	
											data-type="number" 
											data-pk="'.$data->champ->id.'" 
											data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">
										'.$this->escapeHtml($data->nombre).'
									</span>';
								echo '</br></br>';
								break;

							case 'fichier':
								echo 'Fichier actuel : <a href="' . ROOT_DIR . $data->fichier.'">'. $this->escapeHtml(basename($data->fichier)) .'</a></br>';
								echo '<form class="file-input-form" method="POST" action = "'. $this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)) .'">
									<input title="Parcourir" name="file-input" id="'.$data->id.'" type="file">
									<button class="btn btn-primary" type="submit"><i class="icon-ok"> </i> Modifier</button>
    							</form>';
								break;

							case 'url':
								echo '<span class="edit CursorPointer" 
	    									data-name="data" 
	    									data-type="url" 
	    									data-pk="'.$data->champ->id.'" 
    										data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">
    									'.$this->escapeHtml($data->url).'
	    							</span>';
								echo '</br></br>';
								break;

						endswitch ;?>
					</dd>
					<?php endforeach ;?>
				</dl>
			</div>
			
			<div class="tab-pane" id="tab2">
				<h4> Artefacts déjà liés </h4>
				<?php if ($media->artefacts->count() > 0) : ?>
				<table class="table">
					<?php foreach( ($media->artefacts) as $artefact) : ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('media/voirMedia',array('id' => $artefact->id)); ?>">
								<i class="icon-tag"></i>  
								<?php echo $this->escapeHtml($artefact->titre); ?> 
								[<?php echo $this->escapeHtml($artefact->type_element->nom); ?>]
								</a>
							</td>
							<td>
								<!-- Le boutton supprimer déclenche en javascript une modale de confirmation -->
				            	<a href="#" 
				            		data-url="<?php echo $this->url('media/supprimerRelationMediaArtefact', array('idMedia'=>$media->id, 'idArtefact'=>$artefact->id)); ?> "
				            		class="SupprimerRelation">
				            	<i class="icon-trash"></i>
				            	</a>
			            	</td>
						</tr>
					<?php endforeach; ?>
					</table>
				<?php else : ?>
					<p> Aucun artefact n'est lié à ce média. </p>
				<?php endif; ?>
				
				<h4>Lier un nouvel artefact</h4>
				<div class="well">
					<?php echo $this->DatatableWidget('media', array( array('type'=>'type','value'=>'artefact') ) ); ?>
				</div>
			</div>

		</div>
	</div>
</div>

<!-- Contiendra la pop-up de confirmation lors d'un clic sur un bouton 'supprimer' -->
<div id="confirmDiv" >
</div>

<?php $this->inlineScript()->captureStart() ?>

	var element = {'id' : <?php echo $media->id; ?>, 'titre' : '<?php echo $this->escapeHtml($media->titre); ?>', 'description' : '<?php echo $media->description; ?>'};

	$(function () {

		// Gestion du wysihtml5
		$('.textarea-wysihtml5').wysihtml5({
			locale: "fr-FR",
			image: false,
			stylesheets: ["<?php echo $this->basePath() . '/css/bootstrap.css';?>"],
			"events": {
				"load": function() { 
					$(editor.composer.iframe).wysihtml5_size_matters();
				}
			}
		});

		// Enregistrement de la description tapée dans le wysihtml5
		// via un appel ajax
		$("#textarea").on("click",".textarea-submit", function(e){
			DataValue = $('.textarea-wysihtml5').val();
			$.ajax({
				url: "<?php echo $this->url("media/editMedia",array('id'=>$media->id)) ?>",
				type: "POST",
				data:{ name:'description', value: DataValue }, 
		
			}).done(function(){
				$('#textarea-return').html('<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>Enregistrement réussi</div>')
			});
		});
		
		// Modification d'un fichier uploadé (remplacement)
		// via un appel ajax
		$(".file-input-form").on('submit', function (e){
	    	e.preventDefault();
	    	$(this).ajaxSubmit({
				data: {name: 'data'},
				success: function(data) { document.location.reload(); }
            });
	    });
		
		// Gestion du date picker
		$('.picker').editable({
			mode: 'popup',
			placement: 'top',
			format: 'yyyy-mm-dd',
			viewformat: 'dd-mm-yyyy',
			 datepicker: {
				language:'fr',
			}
		
		});
		
		// Gestion de X-Editable
		$('.edit').editable({
			mode: 'inline'
		});
		
		// Modale de confirmation pour la suppression d'une relation avec un artefact
		$(".SupprimerRelation").click(function(event){
        	var dataURL = $(this).attr('data-url');
            $('#confirmDiv').confirmModal({
                heading:'Confirmation',
                body:"Êtes-vous sûr de vouloir supprimer cette relation ?",
                callback: function() {
                     $.post(
                     	dataURL,
                        function(response) {
		                	document.location.reload();
		            	}
                    );
                }
          	});
      	});

    });
    
<?php 
$this->inlineScript()->captureEnd();
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.form.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/dataTables.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/wysihtml5-0.3.0.min.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-wysihtml5.js') ; 
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-wysihtml5.fr-FR.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/editable.wysihtml5.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/jquery.wysihtml5_size_matters.js') ;

?>
