<?php 

$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-wysihtml5.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/css/datepicker.css');

$title = $media->titre;
$this->headTitle($title);
?>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide : modification d'un artefact</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Cette page vous permet de modifier les informations d'un artefact. Tous les champs sont modifiables en cliquant directement dessus.
    	</p>
    	<p>
    	Les onglets 'artefacts liés' et 'médias liés' permettent de gérer les relations mais ne sont pas encore implémentés.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header row-fluid">
	<div class="span9">
		<h1>
		Modification d'un artefact : 
		<span class="edit CursorPointer" data-inputclass="span5" data-name="titre" data-type="text" data-pk="1" data-url="<?php echo $this->url("media/editMedia",array('id'=>$media->id)) ?>"><?php echo $this->escapeHtml($title); ?></span>
		<small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
	</div>

		<a href="<?php echo $this->url('media/voirMedia',
        	array('id' => $media->id)) ?>" class="btn btn-primary span3"><i class="icon-pencil"> </i> Retour à la fiche de ce média</a>
</div>

<div class="row-fluid">
	<div class="span12 well">
		<h3>Description : </h3>
		<div class="wysihtml5 CursorPointer" data-class="input-block-level" data-name="description" data-type="wysihtml5" data-pk="1" data-url="<?php echo $this->url("media/editMedia",array('id'=>$media->id)) ?>"><?php echo $media->description;?></div>
	</div>
</div>
<br>
<div class="row-fluid">
	<div class="span12 well">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-info-sign"></i> Information</a></li>
			<li><a href="#tab2" data-toggle="tab"><i class="icon-sitemap"></i> Artefacts liés</a></li>

		</ul>
		<div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
			<div class="tab-pane active" id="tab1">
				<dl class="dl-horizontal">
					<dt>Type</dt>
					<dd><?php echo $media->type_element->nom; ?></dd>
					<?php 
					foreach( ($media->datas) as $data) :?>
					<dt><?php echo $data->champ->label ?> </dt>
					<dd>
						<?php 
						switch ($data->champ->format) :
						case 'texte':
						echo '<span class="edit CursorPointer" data-name="data" data-type="text" data-pk="1" data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">'.$data->{$data->champ->format}.'</span>';
						break;
						case 'textarea':
						echo '<span class="edit CursorPointer" data-name="data" data-type="text" data-pk="1" data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">'.$data->{$data->champ->format}.'</span>';
						break;
						case 'date':
						echo '<span class="picker CursorPointer" data-name="data" data-type="date" data-pk="1" data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">'.($data->date != null ? $data->date->format('d-m-Y') : "<br/>").'</span>';
						break;
						case 'nombre':
						echo '<span class="edit CursorPointer" data-name="data" data-type="text" data-pk="1" data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">'.$data->{$data->champ->format}.'</span>';
						break;
						case 'fichier':
						echo '<span class="edit CursorPointer" data-name="data" data-type="text" data-pk="1" data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">'.$data->{$data->champ->format}.'</span>';
						break;
						case 'url':
						echo '<span class="edit CursorPointer" data-name="data" data-type="text" data-pk="1" data-url="'.$this->url("media/editMedia",array('id'=> $media->id,'idData'=>$data->id)).'">'.$data->{$data->champ->format}.'</span>';
						break;
						?>
						<?php endswitch ;?>
					</dd>
				<?php endforeach ;?>
				</dl>
			</div>
			<div class="tab-pane" id="tab2">
				<div class="span6">
					<?php $artefacts = array();
					
					foreach( ($media->artefacts) as $artefact) :
						$artefacts[$artefact->semantique->type_destination->id]['nom'] = $artefact->semantique->type_destination->nom;
						$artefacts[$artefact->semantique->type_destination->id]['id'] = $artefact->semantique->type_destination->id;
						$artefacts[$artefact->semantique->type_destination->id]['value'][] = $artefact->origine->titre.
						' '.$artefact->semantique->semantique.
						' <a href="'.$this->url("artefact/voirArtefact",array('id'=>$artefact->destination->id)).'" >'.$artefact->destination->titre.
						'</a><br>';

					endforeach ;
					echo '<div class="tabbable tabs-left"><ul class="nav nav-tabs">';
					$i = 0;
					foreach($artefacts as $key =>$artefact) :
						if ($i == 0){$active = ' class="active"';} else { $active='';}
						echo '<li'.$active.'><a href="#RelA'.$artefact['id'].'" data-toggle="tab">'.$artefact['nom'].'</a></li>';
					$i++;
					endforeach ;
					echo '</ul><div class="tab-content">';
					$i = 0;
					foreach($artefacts as $key =>$artefact) :
						if ($i == 0){$active = ' active';} else { $active='';}
						echo '<div class="tab-pane'.$active.'" id="RelA'.$artefact['id'].'">';

							foreach ($artefact['value'] as $value) {
								echo '<p>'.$value.'</p>';
							}
						echo '</div>';
					$i++;
					endforeach ;
					echo '</div></div>';
					?>
				</div>
				<div class="span6"><?php echo $this->CollectionWidget(); ?></div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">


$('.wysihtml5').editable({
	mode: 'inline',
	wysihtml5 :{
			locale: "fr-FR",
			image: false,
			stylesheets: ["<?php echo $this->basePath() . '/css/bootstrap.css';?>"]
		}
	});
$('.picker').editable({
	mode: 'inline',
	format: 'yyyy-mm-dd',
	viewformat: 'dd-mm-yyyy',
	 datepicker: {
		language:'fr',
	}

});



$('.edit').editable({
	mode: 'inline',
});



</script>
<?php 
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js') ;

$this->headScript()->appendFile($this->basePath() . '/js/wysihtml5-0.3.0.min.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-wysihtml5.js') ; 
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-wysihtml5.fr-FR.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/editable.wysihtml5.js') ;



  
?>
