<?php 
$title = $media->titre;
$this->headTitle($title);
?>

<?php  $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>

<div class="page-header row-fluid">
	<div class="span9">
	<h1><i class="icon-picture"></i> <?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
	</div>
	<?php if ($this->isAllowed('menuCollection') === true) :?>
		<a href="<?php echo $this->url('media/editMedia',array('id' => $media->id)) ?>"
			class="btn btn-primary span3">
			<i class="icon-pencil"> </i> Modifier ce média
		</a>
		<a href="#confirmModal" 
			data-toggle="modal" 
			class="btn btn-danger span3">
			<i class="icon-trash"> </i>  Supprimer ce média
		</a>
    <?php endif; ?>
</div>

<!--Confirm Modal -->
<div id="confirmModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Confirmation : suppression d'un média</h3>
    </div>
    <div class="modal-body">
    	Êtes-vous sur de vouloir supprimer le média "<?php echo $media->titre; ?>" ?
    </div>
    <div class="modal-footer">
	    <a href="<?php echo $this->url('media/removeMedia',
            array('id' => $media->id)) ?>" class="btn btn-primary">Supprimer</a>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="row-fluid">
	<div class="span6">
		<p><?php echo $media->description;?></p>
	</div>
	<div class="span6 well">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-info-sign"></i> Information</a></li>
			<li><a href="#tab2" data-toggle="tab"><i class="icon-sitemap"></i> Artefacts liés</a></li>
		</ul>
		<div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
			<div class="tab-pane active" id="tab1">
				<dl class="dl-horizontal">
					<dt>Type de média </dt>
					<dd>
						<?php 
							echo $media->type_element->nom; 
							echo '</br></br>';
						?>
					</dd>
					<?php foreach( ($media->datas) as $data) :?>
						<?php if ($data->{$data->champ->format} != null): ?>
							<dt><?php echo $data->champ->label ?> 
								<?php if ($data->champ->description != null) : ?>
					        	<a href="#" 
				        			class="description"
				        			rel="popover"
				        			data-content="<?php echo $data->champ->description; ?>"
				        			data-original-title="Description du champ"><i class="icon-question-sign"></i></a>  
				        		<?php endif; ?>
				        	</dt>
							<dd>
								<?php switch ($data->champ->format) :
	        						case 'texte':
	        							echo $data->{$data->champ->format};
										echo '</br></br>';
									break;
									case 'textarea':
										echo $data->{$data->champ->format};
										echo '</br></br>';
									break;
									case 'date':
										echo ($data->date != null ? $data->date->format('d-m-Y') : "<br/>");
										echo '</br></br>';
									break;
									case 'nombre':
										echo $data->{$data->champ->format};
										echo '</br></br>';
									break;
									case 'fichier':
										echo '<a href="'.$data->{$data->champ->format}.'">'.basename($data->{$data->champ->format}).'</a>';
										echo '</br></br>';
									break;
									case 'url':
										echo '<a href="'.$data->{$data->champ->format}.'">'.$data->{$data->champ->format}.'</a>';
										echo '</br></br>';
									break;
									?>
								<?php endswitch ;?>
							</dd>
						<?php endif;?>
					<?php endforeach ;?>
				</dl>
			</div>
			<div class="tab-pane" id="tab2">
				<p> <i class="icon-warning-sign"> </i>  Section en construction... </p>
				<?php /*$artefacts = array();
				
				foreach( ($media->artefacts) as $artefact) :
					$artefacts[$artefact->semantique->type_destination->id]['nom'] = $artefact->semantique->type_destination->nom;
					$artefacts[$artefact->semantique->type_destination->id]['id'] = $artefact->semantique->type_destination->id;
					$artefacts[$artefact->semantique->type_destination->id]['value'][] = $artefact->origine->titre.
					' '.$artefact->semantique->semantique.
					' <a href="'.$this->url("artefact/voirArtefact",array('id'=>$artefact->destination->id)).'" >'.$artefact->destination->titre.
					'</a><br>' ;

					endforeach ;
					echo '<div class="tabbable tabs-left"><ul class="nav nav-tabs">';
					$i = 0;
					foreach($artefacts as $key =>$artefact) :
						if ($i == 0){$active = ' class="active"';} else { $active='';}
						echo '<li'.$active.'><a href="#RelA'.$artefact['id'].'" data-toggle="tab">'.$artefact['nom'].'</a></li>';
					$i++;
					endforeach ;
					echo '</ul><div class="tab-content">';
					$i = 0;
					foreach($artefacts as $key =>$artefact) :
						if ($i == 0){$active = ' active';} else { $active='';}
						echo '<div class="tab-pane'.$active.'" id="RelA'.$artefact['id'].'">';

							foreach ($artefact['value'] as $value) {
								echo '<p>'.$value.'</p>';
							}
						echo '</div>';
					$i++;
					endforeach ;
					echo '</div></div>';*/
					?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

$(".description").popover({placement:'top', trigger:'hover'}); 

$('body').on('click', 'input.span2', function(event) {
	$(this).datepicker({
		showOn: 'focus',
		yearRange: '1900:+0',
		changeMonth: true,
		changeYear: true
	}).focus();
});


</script>

<?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap-datepicker.js'); ?>
