<?php
$title = 'Gestion des Semantique';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<div class="container">
    <a href="<?php echo $this->url('semantique/ajouter') ;?>" class="btn btn-primary"><i class="icon-bookmark"></i> Nouvelle Semantique</a>
    
    <br/><br/>
    
    <table class="table">
    <tr>
        <th>Type origine</th>
        <th>Semantique</th>
        <th>Type destination</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($semantiquesArtefact as $semantique) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($semantique->type_origine->nom);?></td>
        <td><span class="edit CursorPointer" data-name="semantique" data-type="text" data-pk="1" data-url="<?php echo $this->url("semantique/modifier",array('id'=> $semantique->id));?>"><?php echo $this->escapeHtml($semantique->semantique);?></span></td>
        <td><?php echo $this->escapeHtml($semantique->type_destination->nom);?></td>
        <td>
    
            <span class="btn-group">
                <a class="btn btn-danger supprimer" href="#" data-url="<?php echo $this->url('semantique/supprimer',
                array('id' => $semantique->id));?>"><i class="icon-trash"></i> Supprimer</a>
            </span>
        </td>
    </tr>
    <?php endforeach; ?>
    </table>
    
    <div id="confirmDiv" >
    </div>
</div>


<?php 
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js');
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js'); ?>
<script type="text/javascript">
$(".supprimer").on("click", function(){
    var dateURL = $(this).attr('data-url');
    $('#confirmDiv').confirmModal({
        heading:'Confirmation',
        body:"Êtes-vous sûr de vouloir supprimer définitivement la semantique ?",
        callback: function() {
            $(location).attr('href',dateURL);
        }
    });   
}); 
$('.edit').editable({
    mode: 'inline',
});
</script>