<?php
$title = 'Sémantiques des relations entre artefacts';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
?>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide : gestion des sémantiques</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Dans la collection numérique, un artefact peut être reliés à plusieurs autres artefacts. Chaque relation doit être porteuse d'une sémantique, petit texte qui explique la logique de cette relation.
    	</p>
    	<p>
    	Pour avoir des sémantiques cohérentes, ces dernières sont prédéfinies et vous pouvez les gérer sur cette page en tant qu'administrateur de l'application.
    	Lorsqu'un utilisateur décidera de lier deux artefacts entre eux, il aura a choisir une sémantique parmis celle existantes.
    	</p>
    	<p>
    	Une sémantique dépend des types d'artefacts que l'ont relie. Vous pouvez ici modifier ou supprimer une sémantique existante, et en créer de nouvelles.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header row-fluid">
	<div class="span9">
		<h1><?php echo $this->escapeHtml($title); ?> 
	    <small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
	</div>
	<a href="<?php echo $this->url('semantique/ajouter') ;?>" class="btn btn-primary span3"><i class="icon-plus"></i> Ajouter une sémantique</a>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div>
                <table class="table table-striped table-bordered" id="data">
                    <thead>
                        <tr>
                            <th>Type origine</th>
                            <th>Sémantique</th>
                            <th>Type destination</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="5">En cours de téléchargement</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="confirmDiv" >
</div>

<?php 
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js');
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js');
$this->headScript()->appendFile($this->basePath() . '/js/dataTables.js');
?>

<?php $this->inlineScript()->captureStart() ?>
	var table;
	
    $(function() {
		
        table = ResultSet.paginate(
            {
                "aoColumns": [
                                null,
                                null, 
                                null,
                                { "bSortable": false  }
                             ],
                "iColumns": 4,
                "bAutoWidth": false,
                "bSortClasses":false,
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url("semantique"); ?>",
                "fnDrawCallback": function () {
                    $(".SupprimerSemantique").click(function(event){
                        var dateURL = $(this).attr('data-url');
                        var dateValue = $(this).attr('data-value');
                        $('#confirmDiv').confirmModal({
                            heading:'Confirmation',
                            body:"Êtes-vous sûr de vouloir supprimer définitivement la sémantique <br> \""+dateValue+"\" ?",
                            callback: function() {
                                $.post(
                                    dateURL,
                                    { name: "supprimer" },
                                    function(response) {
                                    	document.location.reload();
                                        /*$("#data").dataTable().fnDraw();*/
                                    }
                                );
                            }
                        });   
                    });
                    $('.edit').editable({ mode: 'inline', });
                }
            }
        );

	});
<?php $this->inlineScript()->captureEnd() ?>