
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Créé un nouveau Champ</h3>
  </div>
  <div class="modal-body">
    
	<?php

	$form = $this->form;
	 $form->setAttribute('action', $this->url('album', array('action' => 'add')));
	// $form->setAttribute('method', 'post');

	$form->setAttribute('class','ajChampForm form-horizontal');
	$form->get('label')->setAttribute('placeholder','Label')->setLabelAttributes(array('class' => 'control-label'));
	$form->get('description')->setAttribute('placeholder','Description')->setLabelAttributes(array('class' => 'control-label'));
	$form->get('format')->setLabelAttributes(array('class' => 'control-label'));
	$form->get('submit')->setLabel('Valider')->setAttribute('class','ajChampSubmit btn btn-primary');

	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id')); ?>

	<div class="control-group">
		<?php echo $this->formLabel($form->get('label')) ?>
		<div class="controls">
		<?php echo $this->formInput($form->get('label')) ?>
		<?php echo $this->formElementErrors($form->get('label')) ?>
		</div>
	</div>
	<div class="control-group">
		<?php echo $this->formLabel($form->get('format')) ?>
		<div class="controls">
		<?php echo $this->formSelect($form->get('format')) ?>
		<?php echo $this->formElementErrors($form->get('format')) ?>
		</div>
	</div>
	<div class="control-group">
		<?php echo $this->formLabel($form->get('description')) ?>
		<div class="controls">
		<?php echo $this->formTextarea($form->get('description')) ?>
		<?php echo $this->formElementErrors($form->get('description')) ?>
		</div>
	</div>
	  <div class="modal-footer">
	  	<button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
	  	<a href="#" class="btn btn-primary ajChampSubmit">Ajouter</a>
	<?php //  echo $this->formSubmit($form->get('submit')); ?>
	</div>
	<?php echo $this->form()->closeTag();?>
</div>

