<?php
$title = 'Gestion des types d\'elements';
$this->headTitle($title);
?>

<?php  $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<div class="row">
    <div class="span6">
        <h2>Artefacts
            <a class="ajTypeMedia btn btn-primary " href="#ajTypeMedia" data-url="<?php echo $this->url('typeElement/add',array('media-artefact'=> 'artefact')) ?>"><i class="icon-white icon-plus"></i> Nouveau Type de Medias</a></h2>
            <div class="accordion" id="TEartefact">
                <?php foreach ($TEartefacts as $TEartefact) : ?>
                <div class="accordion-group">

                    <div class="accordion-heading">
                        <a class="accordion-toggle nomValue" pk="nom<?php echo $TEartefact->id ;?>" data-toggle="collapse" data-parent="#TEartefact" href="#collapse<?php echo $TEartefact->id ;?>">
                            <?php echo $TEartefact->nom ;?>
                        </a>
                    </div>
                    <div id="collapse<?php echo $TEartefact->id ;?>" class="accordion-body collapse">
                        <div class="accordion-inner">
                            <h4>Liste des champs : <span class="edit CursorPointer" data-name="nom" data-type="text" data-pk="<?php echo $TEartefact->id ;?>" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEartefact->id)) ?>"><?php echo $TEartefact->nom ;?></span></h4>
                            <dl>
                                <dt class="muted">Titre [text]
                                </dt>
                                <dd></dd>
                                <dt class="muted">Description [textarea]
                                </dt>
                                <dd></dd>
                                <?php foreach ($TEartefact->__get('champs') as $champ) : ?>
                                <dt><a href="#" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEartefact->id,'idChamp'=>$champ->id)) ?>" class="confirmDiv"><i class="icon-white icon-trash"></i></a> <span class="edit CursorPointer" data-name="label" data-type="text" data-pk="1" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEartefact->id,'idChamp'=>$champ->id)) ?>"><?php echo $champ->label;?></span> [<?php echo $champ->format;?>]

                                </dt>
                                <dd><p class="edit CursorPointer" data-name="description" data-inputclass="" data-type="textarea" data-rows="2" data-pk="1" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEartefact->id,'idChamp'=>$champ->id)) ?>"><?php echo $champ->description;?></p></dd>
                                
                            <?php endforeach ;?>
                        </dl>
                        <a class="ajChamp btn btn-primary" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEartefact->id)) ?>" href="#ajChamp"><i class="icon-white icon-plus"></i> Nouveau Champ</a>
                    </div>
                </div>
            </div>
        <?php endforeach ;?>
    </div>

</div>
<div class="span6">
    <h2>Medias <a class="ajTypeMedia btn btn-primary " href="#ajTypeMedia" data-url="<?php echo $this->url('typeElement/add',array('media-artefact'=> 'media')) ?>"><i class="icon-white icon-plus"></i> Nouveau Type de Medias</a></h2>
    <div class="accordion" id="TEmedia">
        <?php foreach ($TEmedias as $TEmedia) : ?>
        <div class="accordion-group">

            <div class="accordion-heading">
                <a class="accordion-toggle nomValue" pk="nom<?php echo $TEmedia->id ;?>" data-toggle="collapse" data-parent="#TEmedia" href="#collapse<?php echo $TEmedia->id ;?>">
                    <?php echo $TEmedia->nom ;?>
                </a>
            </div>
            <div id="collapse<?php echo $TEmedia->id ;?>" class="accordion-body collapse">
                <div class="accordion-inner">
                    <h4>Liste des champs : <span class="edit CursorPointer" data-name="nom" data-type="text" data-pk="<?php echo $TEmedia->id ;?>" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEmedia->id)) ?>"><?php echo $TEmedia->nom ;?></span></h4>
                    <dl>
                        <dt class="muted">Titre [text]
                        </dt>
                        <dd></dd>
                        <dt class="muted">Description [textarea]
                        </dt>
                        <dd></dd>
                        <?php foreach ($TEmedia->__get('champs') as $champ) : ?>
                        

                        <dt><a href="#" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEmedia->id,'idChamp'=>$champ->id)) ?>" class="confirmDiv"><i class="icon-white icon-trash"></i></a> <span class="edit CursorPointer" data-name="label" data-type="text" data-pk="1" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEmedia->id,'idChamp'=>$champ->id)) ?>"><?php echo $champ->label;?></span> [<?php echo $champ->format;?>]

                        </dt>
                        <dd><p class="edit CursorPointer" data-name="description" data-inputclass="" data-type="textarea" data-rows="2" data-pk="1" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEmedia->id,'idChamp'=>$champ->id)) ?>"><?php echo $champ->description;?></p></dd>

                    <?php endforeach ;?>
                </dl>
                <a class="ajChamp btn btn-primary" data-url="<?php echo $this->url("typeElement/editTypeElementAjax",array('id'=>$TEmedia->id)) ?>" href="#ajChamp"><i class="icon-white icon-plus"></i> Nouveau Champ</a>
            </div>
        </div>
    </div>
<?php endforeach ;?>
</div>
</div>
</div>


<div id="modalDiv"></div>

<script type="text/javascript">

$('.edit').on('save', function(e, params) {
    console.info('');
    $('[pk="'+$(this).attr('data-name')+$(this).attr('data-pk')+'"]').html(params.newValue);
});

$('.edit').editable({
    mode: 'inline',
});

$('.confirmDiv').on("click", function(){
    var URL = $(this).attr('data-url');
    $("#modalDiv").confirmModal({
    heading:'Confirmation',
    body:'<div class="container-fluid"><div class="row-fluid"><div class="span2"><i class="icon-warning-sign icon-4x"></i></div><div class="span8"><p>Si vous supprimez ce champ, <strong>toutes les données associées pour tous les artefacts de ce type seront supprimées</strong>.</p><p>Êtes-vous sur de vouloir effectuer cette action ?</p></div><div class="span2"><i class="icon-warning-sign icon-4x"></i></div></div></div>',
    callback: function() {
        $.post( 
            URL,
            { name: "supprimerChamp" },
            function(response) {
                if(response == 'true') {
                location.reload();
            } else {
                alert('Impossible de supprimer ce champ')
            }
            });
    }
});
});

$(".ajChamp").on("click", function(e){
    var URL = $(this).attr('data-url');
    $.ajax({
        url: URL,
        type: "POST",
        data:{ name:'ajChamp', submit:'false' }, 
        success:function(response){
            $('#modalDiv').html('<div id="ChampModal" class="modal">' + response + '</div>').modal();

            $('form.ajChampForm').attr('action', URL);

            console.info($('form.ajChampForm').attr('action')+'::'+ URL);
        },
        error: function(){
            alert('Impossible d\'ajouter des champ');
        }


    });
});
$("#modalDiv").on("click",".ajChampSubmit", function(e){

    var $form = $('.ajChampForm');
    var formatVal = $form.find( 'select[name="format"]' ).val();
    var descriptionVal = $form.find( 'textarea[name="description"]' ).val();
    var labelVal = $form.find( 'input[name="label"]' ).val();
    var URL = $form.attr( 'action' );


    $.ajax({
        url: URL,
        type: "POST",
        data:{ name:'ajChamp', submit:'true', format: formatVal, description: descriptionVal, label: labelVal }, 
        success:function(response){

            if(response == 'true') {
                location.reload();
            } else {

                $('#modalDiv').html('<div id="ChampModal" class="modal">' + response + '</div>').modal();
                $('form.ajChampForm').attr('action', URL);
            }

        },
        error: function(response){
            alert('Impossible d\'ajouter des champ');
        }
    });


});



$(".ajTypeMedia").on("click", function(e){
    var URL = $(this).attr('data-url');
    $.ajax({
        url: URL,
        type: "POST",
        data:{ name:'ajTypeMedia', submit:'false' }, 
        success:function(response){
            $('#modalDiv').html('<div id="ChampModal" class="modal">' + response + '</div>').modal();

            $('form.ajTypeMediaForm').attr('action', URL);

            console.info($('form.ajTypeMediaForm').attr('action')+'::'+ URL);
        },
        error: function(){
            alert('Impossible d\'ajouter des champ');
        }


    });
});
$("#modalDiv").on("click",".ajTypeMediaSubmit", function(e){


    var $form = $('.ajTypeMediaForm');
    var nomVal = $form.find( 'input[name="nom"]' ).val();
    var URL = $form.attr( 'action' );

    $.ajax({
        url: URL,
        type: "POST",
        data:{ name:'ajTypeMedia', submit:'true', nom: nomVal }, 
        success:function(response){

            if(response == 'true') {
                location.reload();
            } else {
                $('#modalDiv').html('<div id="ChampModal" class="modal">' + response + '</div>').modal();
                $('form.ajChampForm').attr('action', URL);
            }

        },
        error: function(response){
            alert('Impossible d\'ajouter des champ');
        }
    });


});

</script>

<?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js') ;?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js') ;?>




















