
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3>Choisir une sémantique</h3>
	</div>

	<div class="modal-body">
		<form class="form-semantiqueArtefact" action="<?php echo $this->escapeHtml($this->url('artefact/addRelationArtefactSemantique', array( 'idOrigine' => $idOrigine, 'idDestination' => $idDestination ))); ?>">
			<dl>
			<?php if( $semantiques != null ) : ?>
				<?php foreach($semantiques as $semantique) : ?>
				
				<label class="radio">
					<dt><input type="radio" name="semantiqueArtefact" id="semantiqueArtefact<?php echo $this->escapeHtml($semantique->id); ?>" value="<?php echo $this->escapeHtml($semantique->id); ?>"><?php echo $this->escapeHtml($semantique->semantique); ?></dt>
				</label>
				
				<?php endforeach; ?>
			<?php else : ?>
			
				<label class="radio">
					<dt> Pas de sémantique correspondante trouvée </dt>
				</label>
				
			<?php endif; ?>
			</dl>
		</form>
		
		<div class="messageSemantique">&nbsp;</div>

	</div>

	<div class="modal-footer">
		<a href="#" class="btn btn-primary ajouterSemantiqueArtefact">Confirmer</a>
		<a href="#" class="btn" data-dismiss="modal">Fermer</a>
	</div>
