<?php
$this->headLink()->prependStylesheet($this->basePath() . '/css/datepicker.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-wysihtml5.css');

$title = 'Création d\'un artefact';
$this->headTitle($title);
?>

<div class="page-header">
    <h1><i class="icon-tag"></i>  <?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<form id="selectform" class="form-horizontal">
	<div class="control-group">
		<label class="control-label" for="inputEmail">Type d'artefact</label>
	    <div class="controls">
			<select name="type" class="target">
				<option value="none">Veuillez choisir un type</option>
				<?php foreach ($this->types as $current) : ?>
					<option value="<?php echo $current->id; ?>" <?php if($current->id == $type_element_id){echo 'selected="selected"';} ?>> <?php echo $current->nom; ?> </option>
				<?php endforeach; ?>
			</select>
	    </div> 
	</div>
</form>
<hr>

<div id="containsform">
<?php if ($form) { 
	$form->setAttribute('action', $this->url('artefact/ajouter', array('type_element_id' => $type_element_id)));
	$form->setAttribute('id','form');
	$form->setAttribute('class','form-horizontal no-submit');
	$form->setAttribute('method', 'post');
	$form->prepare();
	
	// Configure Errors Helper
	$errorsHelper  = $this->plugin('formelementerrors');

	echo $this->form()->openTag($form);
	?>
	
	<div class="row-fluid">
		<div class="span4">

			<?php foreach ($form as $element):
		 	if (!$element instanceof Zend\Form\Element\Button && 
				!$element instanceof Zend\Form\Element\Hidden &&
				$element->getName() != 'description'): ?>
		 		<!-- Label du champ -->
		        <div class="control-group">
			        <label class="control-label">
			        	<?php echo $this->formLabel($element); ?>
			        </label>
			    	<div class="controls">
			    		<!-- Element du formulaire -->
			    		<?php if ($element instanceof Zend\Form\Element\File) { 
			    			echo $this->formFile($element);
			    		} elseif ($element instanceof Zend\Form\Element\Textarea) {
							echo $this->formTextarea($element);
						} elseif ($element instanceof Zend\Form\Element\Date) {
							echo $this->formDate($element);
						} else {
		        			echo $this->formInput($element); 
						} ?> 
		        		<!-- Bulle d'information sur le champ -->
			        	<?php if ($element->getAttribute('description') != null) { ?>
				        	<a href="#" 
			        			id="<?php echo $element->getAttribute('name'); ?>"
			        			class="description"
			        			rel="popover"
			        			data-content="<?php echo $element->getAttribute('description'); ?>"
			        			data-original-title="Description du champ"><i class="icon-question-sign"></i></a>  
			        	<?php } ?>
				        <!-- Erreurs de validation du formulaire -->
				        <?php echo $this->formElementErrors($element); ?>
			        </div> <!-- /controls -->
			    </div> <!-- control-group -->
			<?php endif ?>
		
		<?php endforeach; ?>
		</div>
		
		<!-- Description -->
		<div class="span8 well">
		<?php foreach ($form as $element):
			if ($element->getName() == 'description'): ?>
	        	<!-- Editeur pour la description -->
	        	<?php echo $this->formInput($element); ?>
	        <?php endif; ?>
	    <?php endforeach; ?>
		</div>
	</div>
	
	<!-- Boutton -->
	<?php foreach ($form as $element):
		if ($element instanceof Zend\Form\Element\Button): ?>
	    	<!-- Bouton de validation du formulaire -->
	        <div class="form-actions"> 
	        	<?php echo $this->formSubmit($element); ?>
	        	<a href="<?php echo $this->url('collection/consulter') ?>" role="button" class="btn"> Annuler </a>
	    	</div>
	    <?php endif ?>
	
	<?php endforeach; ?>
	
	<?php echo $this->form()->closeTag(); ?>
<?php } else { ?>
	<div id="annuler">
	        <form class="form-horizontal">
		       	<div class="form-actions">
		       		<a href="<?php echo $this->url('collection/consulter') ?>" role="button" class="btn"> Annuler </a>
		       	</div>
	        </form>
	</div>
	<hr>
	<div id="containsform"></div>
<?php } ?>
</div>

<?php $this->inlineScript()->captureStart() ?>

	$(function () { 

		$(".target").change(function() {
		
		    if($("select option:selected").val()=='none') {
		    	var url="<?php echo $this->url('artefact/ajouter')?>";
				$(location).attr('href',url);
		    } else {
			    var id = $("select option:selected").val();
		    	var url = '<?php echo $this->url('artefact/ajouter', array('type_element_id' => '\'+id+\''))?>';
				$(location).attr('href',url);
		    }
		});

	    $('#containsform').on('click', 'input.picker', function(event) {
	        $(this).datepicker({
	            shown: 'focus',
	            yearRange: '1900:+0',
	            changeMonth: true,
	            changeYear: true,
	            language:'fr',
	            format:'dd-mm-yyyy'
	        }).focus();
	    });
    	
    	$(".description").popover({placement:'top', trigger:'hover'}); 
    	
    	$('.wysihtml5-textarea').wysihtml5({
			locale: "fr-FR",
			image: false,
			stylesheets: ["<?php echo $this->basePath() . '/css/bootstrap.css';?>"],
			"events": {
				"load": function() { 
					$(editor.composer.iframe).wysihtml5_size_matters();
				}
			}
		});
		
    });

<?php $this->inlineScript()->captureEnd() ?>

<?php
	$this->headScript()->appendFile($this->basePath() . '/js/bootstrap.file-input.js');
	$this->headScript()->appendFile($this->basePath() . '/js/wysihtml5-0.3.0.min.js') ;
	$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-wysihtml5.js') ; 
	$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-wysihtml5.fr-FR.js') ;
	$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js');
	$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-datepicker.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.wysihtml5_size_matters.js');
?>
