<h3>Choisissez le type d'artefact à ajouter</h3>

<select name="type" class="target">
	<option value="none">Veuillez choisir un type</option>
	<?php foreach ($this->types as $current) : ?>
		<option value="<?php echo $current->nom; ?>"> <?php echo $current->nom; ?> </option>
	<?php endforeach; ?>
</select>


<div id="containsform"></div>


<script type="text/javascript">
    var select=$(".target");
    select.change(function() {
        if($("select option:selected").val()=='none'){
            $('#containsform').html(' ');
        }
        else{
            //$('#containsform').html('form');
            var requete = $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "<?php echo $this->url('artefact/getFormAjax'); ?>",
                async: false,
    
                data: { type: $("select option:selected").val() }

            })
            .done(function(resp) {
            	//$('#containsform').html(<?php echo $this->form; ?>);
                $('#containsform').html('success type : ' + resp.type);
            })
            .fail(function(jqXHR, textStatus, errorThrown){
            	$('#containsform').html(textStatus + " : " + errorThrown);
            });
        }
    });
</script>