<?php 

$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-wysihtml5.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/pillbox.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/css/datepicker.css');

$title = $artefact->titre;
$this->headTitle($title);
?>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide : modification d'un artefact</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Cette page vous permet de modifier les informations d'un artefact. Tous les champs sont modifiables en cliquant directement dessus.
    	</p>
    	<p>
    	Les onglets 'artefacts liés' et 'médias liés' permettent de gérer les relations mais ne sont pas encore implémentés.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header row-fluid">
	<div class="span9">
		<h1>
		Modification d'un artefact : 
		<small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> <br/>
		<span class="edit CursorPointer" data-inputclass="span12" data-name="titre" data-type="text" data-pk="1" data-url="<?php echo $this->url("artefact/editArtefact",array('id'=>$artefact->id)) ?>"><?php echo $this->escapeHtml($title); ?></span> 
		</h1>
	</div>
	
	<a href="<?php echo $this->url('artefact/voirArtefact',
        	array('id' => $artefact->id)) ?>" class="btn btn-primary span3"><i class="icon-pencil"> </i> Retour à la fiche de cet artefact</a>
	<a href="#confirmModal" data-toggle="modal" class="btn btn-danger span3"><i class="icon-trash"> </i>  Supprimer cet artefact</a>
	
</div>

<!--Confirm Modal -->
<div id="confirmModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Confirmation : suppression d'un artefact</h3>
    </div>
    <div class="modal-body">
    	Êtes-vous sur de vouloir supprimer l'artefact "<?php echo $artefact->titre; ?>" ?
    </div>
    <div class="modal-footer">
	    <a href="<?php echo $this->url('artefact/removeArtefact',
            array('id' => $artefact->id)) ?>" class="btn btn-primary">Supprimer</a>
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>
		
<div class="row-fluid">
	<div class="span6 well">

<form id="textarea">
	<textarea class="textarea-wysihtml5 input-block-level" data-name="description" rows="10" data-url="<?php echo $this->url("artefact/editArtefact",array('id'=>$artefact->id)) ?>"><?php echo $artefact->description;?></textarea>
	<button type="button" class="textarea-submit btn btn-primary editable-submit"><i class="icon-ok icon-white"></i> Enregistrer</button>
</form>

<div id="textarea-return"></div>
	</div>
	<div class="span6 well">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-info-sign"></i> Information</a></li>
			<li><a href="#tab2" data-toggle="tab"><i class="icon-sitemap"></i> Artefacts liés</a></li>
			<li><a href="#tab3" data-toggle="tab"><i class="icon-sitemap"></i> Médias liés</a></li>
		</ul>
		
		<div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
			<div class="tab-pane active" id="tab1">
				<dl>
					<dt>Type d'artefact</dt>
					<dd>
						<?php 
							echo $artefact->type_element->nom; 
							echo '</br></br>';
						?>
					</dd>
					<?php foreach($datas as $data) :?>
					<dt>
						<?php echo $data->champ->label ?> 
						<?php if ($data->champ->description != null) : ?>
				        	<a href="#" 
			        			class="description"
			        			rel="popover"
			        			data-content="<?php echo $data->champ->description; ?>"
			        			data-original-title="Description du champ"><i class="icon-question-sign"></i></a>  
			        	<?php endif; ?>
					</dt>
					<dd>
						<?php 
						switch ($data->champ->format) :
							case 'texte':
								echo '<span class="edit CursorPointer" 
										data-name="data" 
										data-type="text" 
										data-pk="'.$data->champ->id.'" 
										data-url="'.$this->url("artefact/editArtefact",array('id'=> $artefact->id,'idData'=>$data->id)).'">
									'.$data->texte.'
								</span>';
								echo '</br></br>';
								break;

							case 'textarea':
								echo '<span class="edit CursorPointer" 
										data-name="data" 
										data-type="textarea" 
										data-pk="'.$data->champ->id.'" 
										data-url="'.$this->url("artefact/editArtefact",array('id'=> $artefact->id,'idData'=>$data->id)).'">
	    							'.$data->textarea.'
    							</span>';
								echo '</br></br>';
								break;

							case 'date':
								if($data->date === null){
									$date = null;
								} else {
									$date = $data->date->format('d-m-Y');
								}
								echo '<span class="picker CursorPointer" 
    										data-name="data" 
    										data-type="date" 
    										data-pk="'.$data->champ->id.'" 
	    									data-url="'.$this->url("artefact/editArtefact",array('id'=> $artefact->id,'idData'=>$data->id)).'">
										'.$date.'
									</span>';
								echo '</br></br>';
								break;
							
							case 'nombre':
								echo '<span class="edit CursorPointer" 
											data-name="data" 
											data-type="number" 
											data-pk="'.$data->champ->id.'" 
											data-url="'.$this->url("artefact/editArtefact",array('id'=> $artefact->id,'idData'=>$data->id)).'">
										'.$data->nombre.'
									</span>';
								echo '</br></br>';
								break;

							case 'url':
								echo '<span class="edit CursorPointer"
										data-name="data"
										data-type="url"
										data-pk="'.$data->champ->id.'"
	    								data-url="'.$this->url("artefact/editArtefact",array('id'=> $artefact->id,'idData'=>$data->id)).'">
	    							'.$data->url.'
    							</span>';
								echo '</br></br>';
								break;
									
							case 'fichier':
								echo 'Fichier actuel : <a href="' . ROOT_DIR . $data->fichier.'">'. basename($data->fichier) .'</a></br>';
								echo '<form class="file-input-form" method="POST" action = "'. $this->url("artefact/editArtefact",array('id'=> $artefact->id,'idData'=>$data->id)) .'">
									<input title="Parcourir" name="file-input" id="'.$data->id.'" type="file">
									<button class="btn btn-primary" type="submit"><i class="icon-ok"> </i> Modifier</button>
    							</form>';
								break;

						endswitch ;?>
					</dd>
				<?php endforeach ;?>
				</dl>
			</div>
			
			<div class="tab-pane" id="tab2">
				<p> <i class="icon-warning-sign"> </i>  Section en construction... </p>
				
					<?php 
					/*
					$relations_artefacts = array();
					
					foreach( ($artefact->relations_artefacts) as $relation_artefact) :
						$relations_artefacts[$relation_artefact->semantique->type_destination->id]['nom'] = $relation_artefact->semantique->type_destination->nom;
						$relations_artefacts[$relation_artefact->semantique->type_destination->id]['id'] = $relation_artefact->semantique->type_destination->id;
						$relations_artefacts[$relation_artefact->semantique->type_destination->id]['value'][] = $relation_artefact->origine->titre.
						' '.$relation_artefact->semantique->semantique.
						' <a href="'.$this->url("artefact/voirArtefact",array('id'=>$relation_artefact->destination->id)).'" >'.$relation_artefact->destination->titre.
						'</a><br>' ;

					endforeach ;
					echo '<div class="tabbable tabs-left"><ul class="nav nav-tabs">';
					$i = 0;
					foreach($relations_artefacts as $key =>$relation_artefact) :
						if ($i == 0){$active = ' class="active"';} else { $active='';}
						echo '<li'.$active.'><a href="#RelA'.$relation_artefact['id'].'" data-toggle="tab">'.$relation_artefact['nom'].'</a></li>';
					$i++;
					endforeach ;
					echo '</ul><div class="tab-content">';
					$i = 0;
					foreach($relations_artefacts as $key =>$relation_artefact) :
						if ($i == 0){$active = ' active';} else { $active='';}
						echo '<div class="tab-pane'.$active.'" id="RelA'.$relation_artefact['id'].'">';

							foreach ($relation_artefact['value'] as $value) {
								echo '<p>'.$value.'</p>';
							}
						echo '</div>';
					$i++;
					endforeach ;
					echo '</div></div>';
					*/
					?>
				

				<?php echo $this->CollectionWidget(array( array('type'=>'type','value'=>'artefact') ) ); ?>


			</div>
			<div class="tab-pane" id="tab3">
				<p> <i class="icon-warning-sign"> </i>  Section en construction... </p>
				<div class="span6">
					<?php //foreach( ($artefact->medias) as $media) :?>
						<?php //echo $media->type_element->nom ?>
					<?php //endforeach ;?>
					<!-- 
					<div class="tabbable tabs-left ">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#rA" data-toggle="tab">Section 1</a></li>
							<li><a href="#rB" data-toggle="tab">Section 2</a></li>
							<li><a href="#rC" data-toggle="tab">Section 3</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="rA">
								<p>I'm in Section A.</p>
							</div>
							<div class="tab-pane" id="rB">
								<p>Howdy, I'm in Section B.</p>
							</div>
							<div class="tab-pane" id="rC">
								<p>What up girl, this is Section C.</p>
							</div>
						</div>
					</div>
					-->
				</div>
				<div class="span6"><?php //echo $this->CollectionWidget(); ?></div>
			</div>
		</div>
	</div>
</div>

<?php $this->inlineScript()->captureStart() ?>

	$(function () {

		$('.textarea-wysihtml5').wysihtml5({
			locale: "fr-FR",
			image: false,
			stylesheets: ["<?php echo $this->basePath() . '/css/bootstrap.css';?>"],
			"events": {
				"load": function() { 
					$(editor.composer.iframe).wysihtml5_size_matters();
				}
			}
		});

		$("#textarea").on("click",".textarea-submit", function(e){
		DataValue = $('.textarea-wysihtml5').val();
			$.ajax({
				url: "<?php echo $this->url("artefact/editArtefact",array('id'=>$artefact->id)) ?>",
				type: "POST",
				data:{ name:'description', value: DataValue }, 
		
			}).done(function(){
				$('#textarea-return').html('<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>Enregistrement réussi</div>')
			});
		});

	    $(".file-input-form").on('submit', function (e){
	    	e.preventDefault();
	    	$(this).ajaxSubmit({
				data: {name: 'data'},
				success: function(data) { document.location.reload(); }
            });
	    });

		$('.picker').editable({
			mode: 'popup',
			placement: 'top',
			format: 'yyyy-mm-dd',
			viewformat: 'dd-mm-yyyy',
			 datepicker: {
				language:'fr',
			}
		});
		
		$('.edit').editable({
			mode: 'inline',
		});
		
    });
    
<?php 

$this->inlineScript()->captureEnd();

$this->headScript()->appendFile($this->basePath() . '/js/jquery.form.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/dataTables.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/pillbox.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/wysihtml5-0.3.0.min.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-wysihtml5.js') ; 
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-wysihtml5.fr-FR.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/editable.wysihtml5.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/jquery.wysihtml5_size_matters.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap.file-input.js');

?>
