<script type="text/javascript">
	function fonction(objet) {
	    
	}
</script>

<select name="nom_select" onchange="fonction(this);">
	<?php foreach ($this->types as $current) : ?>
		<option value="<?php echo $current->nom; ?>"> <?php echo $current->nom; ?> </option>
	<?php endforeach; ?>
</select>
<br>
<a href="<?php echo $this->url('artefact/ajouter') ?>" class="btn icon-plus btn-primary">Ajouter un artefact</a>

