<?php 
$title = $artefact->titre;
$this->headTitle($title);
?>

<?php  $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>

<div class="page-header row-fluid">
	<div class="span9">
	<h1><i class="icon-tag"></i> <?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
	</div>
	<?php if ($this->isAllowed('menuCollection') === true) :?>
		<a href="<?php echo $this->url('artefact/editArtefact',
            array('id' => $artefact->id)) ?>" class="btn btn-primary span3"><i class="icon-pencil"> </i> Modifier cet artefact</a>
    <?php endif; ?>
</div>

<div class="row-fluid">
	<div class="span7">
		<p><?php echo $artefact->description;?></p>
	</div>
	<div class="span5 well">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-info-sign"></i> Information</a></li>
			<li><a href="#tab2" data-toggle="tab"><i class="icon-sitemap"></i> Artefacts liés</a></li>
			<li><a href="#tab3" data-toggle="tab"><i class="icon-sitemap"></i> Medias</a></li>
		</ul>
		<div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
			<div class="tab-pane active" id="tab1">
				<dl class="dl-horizontal">
					<dt>Type</dt>
					<dd><?php echo $artefact->type_element->nom; ?></dd>
					<?php foreach( ($artefact->datas) as $data) :
					if($data->{$data->champ->format} != null)
					{
						?>
						<dt><?php echo $data->champ->label ?> </dt>
						<dd>
							<?php switch ($data->champ->format) :
        						case 'texte':
        							echo $data->{$data->champ->format};
								break;
								case 'textarea':
									echo $data->{$data->champ->format};
								break;
								case 'date':
									echo $data->date->format('d-m-Y');
								break;
								case 'nombre':
									echo $data->{$data->champ->format};
								break;
								case 'fichier':
									echo '<a href="'.$data->{$data->champ->format}.'">'.$data->{$data->champ->format}.'</a>';
								break;
								case 'url':
									echo '<a href="'.$data->{$data->champ->format}.'">'.$data->{$data->champ->format}.'</a>';
								break;
								?>
							<?php endswitch ;?>
						</dd>
					<?php
					}
					endforeach ;?>
				</dl>
			</div>
			<div class="tab-pane" id="tab2">

					<?php $relations_artefacts = array();
					
					foreach( ($artefact->relations_artefacts) as $relation_artefact) :
						$relations_artefacts[$relation_artefact->semantique->type_destination->id]['nom'] = $relation_artefact->semantique->type_destination->nom;
						$relations_artefacts[$relation_artefact->semantique->type_destination->id]['id'] = $relation_artefact->semantique->type_destination->id;
						$relations_artefacts[$relation_artefact->semantique->type_destination->id]['value'][] = $relation_artefact->origine->titre.
						' '.$relation_artefact->semantique->semantique.
						' <a href="'.$this->url("artefact/voirArtefact",array('id'=>$relation_artefact->destination->id)).'" >'.$relation_artefact->destination->titre.
						'</a><br>' ;

						endforeach ;
						echo '<div class="tabbable tabs-left"><ul class="nav nav-tabs">';
						$i = 0;
						foreach($relations_artefacts as $key =>$relation_artefact) :
							if ($i == 0){$active = ' class="active"';} else { $active='';}
							echo '<li'.$active.'><a href="#RelA'.$relation_artefact['id'].'" data-toggle="tab">'.$relation_artefact['nom'].'</a></li>';
						$i++;
						endforeach ;
						echo '</ul><div class="tab-content">';
						$i = 0;
						foreach($relations_artefacts as $key =>$relation_artefact) :
							if ($i == 0){$active = ' active';} else { $active='';}
							echo '<div class="tab-pane'.$active.'" id="RelA'.$relation_artefact['id'].'">';

								foreach ($relation_artefact['value'] as $value) {
									echo '<p>'.$value.'</p>';
								}
							echo '</div>';
						$i++;
						endforeach ;
						echo '</div></div>';
						?>
				
				</div>
				<div class="tab-pane" id="tab3">
						<?php foreach( ($artefact->medias) as $media) :?>
							<?php echo $media->type_element->nom ?>
						<?php endforeach ;?>
				</div>
			</div>
		</div>
	</div>
</div>





<script type="text/javascript">

$('body').on('click', 'input.span2', function(event) {
	$(this).datepicker({
		showOn: 'focus',
		yearRange: '1900:+0',
		changeMonth: true,
		changeYear: true
	}).focus();
});


</script>

<?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap-datepicker.js'); ?>