<?php 
$title = $artefact->titre;
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
?>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Vous êtes sur la fiche d'un artefact. Cette page permet de consulter les informations relatives à un artefact.
    	</p>
    	<p>
    	La description détaillée de l'artefact se trouve à gauche. Le menu à droite permet de voir les valeurs des champs pour cet artefacts, les liaisons (avec sémantique) vers d'autres artefact et les liaisons vers des médias.
    	</p>
    	<p>
    	Si vous avez l'autorisation, vous pouvez modifier les informations de cet artefact grâce au bouton en haut à gauche.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header row-fluid">
	<div class="span9">
	<h1><i class="icon-tag"></i> <?php echo $this->escapeHtml($title); ?> 
	<small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
	</div>
	<?php if ($this->isAllowed('Collection') === true) :?>
		<a href="<?php echo $this->url('artefact/editArtefact',array('id' => $artefact->id)) ?>" 
			class="btn btn-primary span3">
			<i class="icon-pencil"> </i> Modifier cet artefact
		</a>
		<a href="#confirmModal" 
			data-toggle="modal" 
			class="btn btn-danger span3">
			<i class="icon-trash"> </i>  Supprimer cet artefact
		</a>
    <?php endif; ?>
</div>

<!--Confirm Modal -->
<div id="confirmModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Confirmation : suppression d'un artefact</h3>
    </div>
    <div class="modal-body">
    	Êtes-vous sur de vouloir supprimer l'artefact "<?php echo $this->escapeHtml($artefact->titre); ?>" ?
    </div>
    <div class="modal-footer">
	    <a href="<?php echo $this->url('artefact/removeArtefact',
            array('id' => $artefact->id)) ?>" class="btn btn-primary">Supprimer</a>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="row-fluid">
	<div class="span6">
		<p><?php echo $artefact->description;?></p> <!-- créé avec le wysihtml5 donc pas de escapehtml -->
	</div>
	<div class="span6 well">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-info-sign"></i> Informations</a></li>
			<li><a href="#tab2" data-toggle="tab"><i class="icon-sitemap"></i> Artefacts liés</a></li>
			<li><a href="#tab3" data-toggle="tab"><i class="icon-sitemap"></i> Médias liés</a></li>
		</ul>
		<div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
			<div class="tab-pane active" id="tab1">
				<dl>
					<dt>Type d'artefact</dt>
					<dd>
						<?php 
							echo $this->escapeHtml($artefact->type_element->nom); 
							echo '</br></br>';
						?>
					</dd>

					<?php foreach( ($ChampsDatasElement) as $champData) : ?>
						<dt>
							<?php echo $this->escapeHtml($champData['label']); ?> 
							<?php if ($champData['description'] != null) : ?>
					       	<a href="#" 
				        		class="description"
				        		rel="popover"
				        		data-content="<?php echo $this->escapeHtml($champData['description']); ?>"
				        		data-original-title="Description du champ"><i class="icon-question-sign"></i></a>  
				        	<?php endif; ?>
						</dt>
						<dd>
							<?php 
							// Valeur si le data n'est pas renseigné
							$null = 'Non renseigné';

							switch ($champData['format']) :
	        					case 'texte':
	        						echo ($champData['data']) ? $this->escapeHtml($champData['data']->texte) : $null ;
									echo '</br></br>';
								break;
								case 'textarea':
									echo ($champData['data']) ? $this->escapeHtml($champData['data']->textarea) : $null ;
									echo '</br></br>';
								break;
								case 'date':
									if ($champData['data']) {
										echo ($champData['data']->date) ? $champData['data']->date->format('Y-d-m') : $null ;
									} else {
										echo $null;
									}

									echo '</br></br>';
								break;
								case 'nombre':
									echo ($champData['data']) ? $this->escapeHtml($champData['data']->nombre) : $null ;
									echo '</br></br>';
								break;
								case 'fichier':
									echo ($champData['data']) ? '<a href="' . ROOT_DIR . $champData['data']->fichier.'">'.$this->escapeHtml(basename($champData['data']->fichier)).'</a>' : $null ;
									echo '</br></br>';
								break;
								case 'url':
									echo ($champData['data']) ? '<a href="' . $champData['data']->url.'">'.$this->escapeHtml($champData['data']->url).'</a>' : $null ;
									echo '</br></br>';
								break;
								?>
							<?php endswitch ;?>
						</dd>
					<?php endforeach ; ?>

				</dl>
			</div>
			
			<div class="tab-pane" id="tab2">
				<?php if ($relations_out != null || $relations_in != null) : ?>
					<table class="table">
					<tr>
						<th> Origine  </th>
						<th> Sémantique  </th>
						<th> Destination </th>
					</tr>
					<?php foreach($relations_out as $relation) : ?>
						<tr>
							<td> <?php echo $this->escapeHtml($artefact->titre); ?>  </td>
							<td> <?php echo $this->escapeHtml($relation->semantique->semantique); ?>  </td>
							<td>
								<a href="<?php echo $this->url('artefact/voirArtefact',array('id' => $relation->destination->id)); ?>">
								<i class="icon-tag"></i>
								<?php echo $this->escapeHtml($relation->destination->titre); ?> 
								[<?php echo $this->escapeHtml($relation->destination->type_element->nom); ?>]
								</a>
							</td>
						</tr>
					<?php endforeach; ?>
					<?php foreach($relations_in as $relation) : ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('artefact/voirArtefact',array('id' => $relation->origine->id)); ?>">
								<i class="icon-tag"></i>
								<?php echo $this->escapeHtml($relation->origine->titre); ?> 
								[<?php echo $this->escapeHtml($relation->origine->type_element->nom); ?>]
								</a>
							</td>
							<td> <?php echo $this->escapeHtml($relation->semantique->semantique); ?>  </td>
							<td> <?php echo $this->escapeHtml($artefact->titre); ?>  </td>
						</tr>
					<?php endforeach; ?>
					</table>
				<?php else : ?>
					<p> Aucun artefact n'est lié à cet artefact. </p>
				<?php endif; ?>
			</div>
			
			<div class="tab-pane" id="tab3">
				<?php if ($artefact->medias->count() > 0) : ?>
					<table class="table">
					<?php foreach( ($artefact->medias) as $media) : ?>
						<tr>
						<td>
							<a href="<?php echo $this->url('media/voirMedia',array('id' => $media->id)); ?>">
							<i class="icon-picture"></i>  
							<?php echo $this->escapeHtml($media->titre); ?>
							[<?php echo $this->escapeHtml($media->type_element->nom); ?>] 
							</a>
						</td>
						</tr>
					<?php endforeach; ?>
					</table>
				<?php else : ?>
					<p> Aucun média n'est lié à cet artefact. </p>
				<?php endif; ?>
			</div>

		</div>
	</div>
</div>

<?php $this->inlineScript()->captureStart(); ?>

	var element = {'id' : <?php echo $artefact->id; ?>, 'titre' : '<?php echo $this->escapeHtml($artefact->titre); ?>' };

	$(function () {
							
		$(".description").popover({placement:'top', trigger:'hover'}); 
		
		$('body').on('click', 'input.span2', function(event) {
			$(this).datepicker({
				showOn: 'focus',
				yearRange: '1900:+0',
				changeMonth: true,
				changeYear: true
			}).focus();
		});

    });
    
<?php 
$this->inlineScript()->captureEnd(); 

$this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/ResultSet.js'); 
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-datepicker.js'); 
?>