<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Cervin')->setSeparator(' - ')->setAutoEscape(false) ?>
    
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    
        <!-- Le styles -->
        <?php  $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/aconit.bmp')); ?>

        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-all.css'); ?>

        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-all.js') ;?>
        <?php echo $this->headStyle() ?>
   </head>
   <body>
        <div class="navbar navbar-inverse ">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home'); ?>">Cervin</a>

                        <ul class="nav">
                            <li class="divider-vertical"></li>

                            <li class="active"><a href="<?php echo $this->url('home'); ?>"><i class="icon-home"></i>  Accueil</a></li>

                            <li class="divider-vertical"></li>
                            
							<?php $role = null; ?>
                            <?php if($this->zfcUserIdentity()): ?>
                                <?php $tmp=$this->zfcUserIdentity()->getRoles();
                                $role=$tmp[0]->getRoleId(); ?>
                                <?php if($role == 'Collection' || $role == 'Parcours' || $role == 'Admin'): ?>
                                	<li><a href="<?php echo $this->url('collection/consulter'); ?>"><i class="icon-save"></i>  Collection Numérique</a></li>
                                	<li class="divider-vertical"></li>
                                <?php endif; ?>
                                <?php if($role == 'Parcours' || $role == 'Admin'): ?>
                                    <li><a href="#"><i class="icon-road"></i>  Parcours</a></li>
                                    <li class="divider-vertical"></li>
                                <?php endif; ?>
                            <?php endif; ?>
                        </ul>

                        <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                        
                        	<?php 
                                if($this->zfcUserIdentity()):
                                    if($role == 'Admin'): ?>
                                    	<li class="divider-vertical"></li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-tasks"></i>  Administration<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="<?php echo $this->url('admin/gestion-users'); ?>"><i class="icon-group"></i>  Gestion des utilisateurs</a></li>
                                                <li><a href="<?php echo $this->url('typeElement'); ?>"><i class="icon-sitemap"></i>  Gestion des types d'elements</a></li>
                                            </ul>
                                        </li>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php if(!$this->zfcUserIdentity()): ?>
                            	<li class="divider-vertical"></li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">Connexion<strong class="caret"></strong></a>
                                    <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
                                        <?php echo $this->zfcUserLoginWidget(); ?>
                                    </div>
                                </li>
                            <?php else: ?>
                            	<li class="divider-vertical"></li>
                                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-user"></i>  <?php echo $this->zfcUserIdentity()->getDisplayName(); ?> <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/user"><i class="icon-user"></i> Mon compte</a></li>
                                        <li><a href="/user/logout"><i class="icon-off"></i> Déconnexion</a></li>
                                    </ul>
                                </li>
                            <?php endif?>
                        </ul>

                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">
            <?php echo $this->content; ?>
        </div>

        <hr>
            <footer>
                <p class="container">&copy; <?php echo date("Y"); ?> - Cervin</p>
            </footer>
    </body>
    <?php echo $this->inlineScript() ?>
</html>



















