<?php
$title = 'Sémantique des transitions entre scènes';
$this->headTitle($title);
?>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide : sémantique des transitions entre scènes</h3>
    </div>
    <div class="modal-body">
    	A ECRIRE
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>


<div class="page-header row-fluid">
	<div class="span9">
		<h1><?php echo $this->escapeHtml($title); ?> 
	    <small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
	</div>
	<a href="<?php echo $this->url('semantiquetransition/ajouter') ?>" class="btn btn-primary span3"><i class="icon-white icon-plus"></i> Ajouter une sémantique </a>
</div>

<table class="table table-striped">
	<tr>
		<th>Sémantique</th>
		<th>Description</th>
		<th></th>
	</tr>
	<?php foreach ($semantiques as $semantique): ?>
		<tr>
			<!-- <td><?php echo $semantique->semantique; ?></td> -->
			<td>
				<span class="edit CursorPointer"
                    	data-url="<?php echo $this->url("semantiquetransition/modifier", array("id" => $semantique->id)); ?>"
                    	data-name="semantique" 
                    	data-type="text" 
                    	data-pk="1">
            		<?php  echo $semantique->semantique ?>
                </span>
            </td>
            <td>
				<span class="edit CursorPointer"
                    	data-url="<?php echo $this->url("semantiquetransition/modifier", array("id" => $semantique->id)); ?>"
                    	data-name="description" 
                    	data-type="textarea" 
                    	data-pk="1">
            		<?php  echo $semantique->description ?>
                </span>
            </td>
            <td>
            	<a href="#" 
            		data-url="<?php echo $this->url('semantiquetransition/supprimer', array('id' => $semantique->id)); ?> "
            		data-value="<?php  echo $semantique->semantique ?>"
            		class="btn btn-danger SupprimerSemantique">
            	<i class="icon-trash"></i> Supprimer
            	</a>
            </td>
		</tr>
	<?php endforeach; ?>
</table> 

<div id="confirmDiv" >
</div>

<?php 
	$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js');
	$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js');
?>

<?php $this->inlineScript()->captureStart() ?>
	
	$(function() {
		
		$('.edit').editable({ mode: 'inline', });
		
		$(".SupprimerSemantique").click(function(event){
        	var dataURL = $(this).attr('data-url');
            var dataValue = $(this).attr('data-value');
            $('#confirmDiv').confirmModal({
                heading:'Confirmation',
                body:"Êtes-vous sûr de vouloir supprimer définitivement la sémantique <i>" + dataValue + " </i>?",
                callback: function() {
                     $.post(
                     	dataURL,
                        { name: "supprimer" },
                        function(response) {
		                	if(response == 'true') {
		                		document.location.reload();
							} else {
		                		alert("La sémantique ne peut pas être supprimée, elle est probablement utilisée dans une transition existante");
		           			}
		            	}
                    );
                }
          	});
      	});
      	
	});
	
<?php $this->inlineScript()->captureEnd() ?>
