<h3>Changement d'Email pour <?php echo $this->zfcUserDisplayName() ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">L'adresse Email a été modifiée avec succès.</div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">Impossible de modifier l'adresse. Veuillez réessayer.</div>
<?php endif; ?>
<?php

$form = $this->changeEmailForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changeemail'));
$form->setAttribute('method', 'post');
$form->get('newIdentity')->setLabel('Nouvel Email')->setAttribute('placeholder','nouvelEmail@exemple.com');
$form->get('newIdentityVerify')->setLabel('Vérification nouvel Email')->setAttribute('placeholder','nouvelEmail@exemple.com');
$form->get('credential')->setLabel('Mot de passe')->setAttribute('placeholder','******');

?>
<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
    <?php foreach ($form as $element): ?>
        <?php if ($element->getLabel() != null): ?>
            <dt><?php echo $this->formLabel($element) ?></dt>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <dd><?php echo $this->formButton($element) ?></dd>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
        <?php else: ?>
            <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
        <?php endif ?>
    <?php endforeach ?>
    </dl>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
    <?php endif ?>
    <input type="submit" value="Valider" class="btn btn-success" />
<?php echo $this->form()->closeTag() ?>
