<h3>Changement de mot de passe pour <?php echo $this->zfcUserDisplayName() ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">Le mot de passe a été modifié avec succès.</div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">Impossible de modifier le mot de passe. Veuillez réessayer.</div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$form->get('newCredential')->setLabel('Nouveau mot de passe')->setAttribute('placeholder','******');
$form->get('newCredentialVerify')->setLabel('Vérification nouveau mot de passe')->setAttribute('placeholder','******');
$form->get('credential')->setLabel('Mot de passe')->setAttribute('placeholder','******');
$form->get('submit')->setValue('Valider')->setAttribute('class','btn btn-success');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>
<dl class="zend_form">
<?php echo $this->formElementErrors($form->get('identity')); ?>
<dd><?php echo $this->formInput($form->get('identity')); ?></dd>

<dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
<dd><?php
echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
?></dd>

<dt><?php echo $this->formLabel($form->get('newCredential')); ?></dt>
<dd><?php
echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
?></dd>

<dt><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></dt>
<dd><?php
echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
?></dd>

<dd><?php
//echo $this->formInput($form->get('csrf'));
echo $this->formInput($form->get('submit'));
?></dd>

</dl>

<?php echo $this->form()->closeTag(); ?>
