<h3>Changement de mot de passe pour <?php echo $this->zfcUserDisplayName() ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">Le mot de passe a été modifié avec succès. (Vous allez être redirigé)</div>
<script type="text/javascript">
    function delayer(){
        window.location = "/user";
    }
    setTimeout('delayer()', 3000);
</script>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">Impossible de modifier le mot de passe. Veuillez réessayer.</div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$form->setAttribute('class','form-horizontal');
$form->get('newCredential')->setLabel('Nouveau mot de passe')->setAttribute('placeholder','******')->setLabelAttributes(array('class' => 'control-label'));
$form->get('newCredentialVerify')->setLabel('Confirmation')->setAttribute('placeholder','******')->setLabelAttributes(array('class' => 'control-label'));
$form->get('credential')->setLabel('Mot de passe')->setAttribute('placeholder','******')->setLabelAttributes(array('class' => 'control-label'));
$form->get('submit')->setValue('Valider')->setAttribute('class','btn btn-success');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>

<?php echo $this->formElementErrors($form->get('identity')); ?>
<?php echo $this->formInput($form->get('identity')); ?>

<div class="control-group">
	<?php echo $this->formLabel($form->get('credential')); ?>
	<div class="controls">
		<?php
		echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
		?>
	</div>
</div>
	
<div class="control-group">
	<?php echo $this->formLabel($form->get('newCredential')); ?>
	<div class="controls">
		<?php
		echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
		?>
	</div>
</div>
	
<div class="control-group">
	<?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
	<div class="controls">
		<?php
		echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
		?>
	</div>
</div>

<div class="form-actions">
	<?php
	echo $this->formInput($form->get('submit'));
	?>
</div>


<?php echo $this->form()->closeTag(); ?>
