<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3>Hello, <?php echo $this->zfcUserDisplayName() ?>!</h3><br>
<div style="margin-top:25px; margin-left:50px;">
	
	<table border="1">
		<tr>
			<!-- modify infos -->
			<td class="span2">Email :</td>
			<td class="span3"><?php echo $this->zfcUserIdentity()->getEmail(); ?></td>
			<td class="span1"><a href="#">Modifier</a></td>
		</tr>

		<tr>
			<!-- modify password -->
			<td class="span2">Mot de passe :</td>
			<td class="span3">********</td>
			<td class="span1"><a href="#">Modifier</a></td>
		</tr>
	</table>
</div>

<br><a href="<?php echo $this->url('zfcuser/logout') ?>">Déconnexion</a>
<div style="clear:both;"></div>
