<?php if($this->statut):
	if($this->source == "email"): ?>
		<div class="alert alert-success">L'adresse Email a été modifiée avec succès.</div>
	<?php endif;
	if($this->source == "password"): ?>
		<div class="alert alert-success">Le mot de passe a été modifié avec succès.</div>
	<?php endif; ?>
<?php endif; ?>
<?php

$title = 'Mon compte';
$this->headTitle($title);
?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<div class="row-fluid">
	<div class="span6 well">
		<h4>Profil</h4>
	    <div class="row-fluid">
		    <div class="span6">
		    	<a class="thumbnail"><img src="http://critterapp.pagodabox.com/img/user.jpg" alt=""></a>
		    	<a href="<?php echo $this->url('zfcuser/logout') ?>" role="button" class="btn btn-danger btn-block" >
		    		<i class="icon-off"></i>  Déconnexion</a>
		    </div>
		    <div class="span6">
		    	<p><strong><?php echo $this->zfcUserDisplayName() ?></strong> (<?php echo $this->zfcUserIdentity()->getEmail(); ?>)</p>
				<a href="<?php echo $this->url('zfcuser/changeemail'); ?>" role="button" class="btn btn-primary btn-block"> <i class="icon-pencil"></i>  Changer mon mail </a>
				
				<a href="<?php echo $this->url('zfcuser/changepassword'); ?>" role="button" class="btn btn-primary btn-block"> <i class="icon-pencil"></i>  Changer mon mot de passe </a>
		    </div>
	    </div>
	</div>
	
	<div class="span6 well">
	    <h4>Droits</h4>
	    
	    <div class="row-fluid">
		    <div class="span6">
		    	<p> Vous avez le rôle <strong><?php $roles = $this->zfcUserIdentity()->getRoles();
		    	
							  $role = $roles[0]->getRoleId(); 
							  echo $role; ?></strong> </p>
				<?php if ($this->zfcUserIdentity()->getAttenteRole()) {
					echo '<p>Votre demande de role "<strong>'.$this->zfcUserIdentity()->getAttenteRole()->getRoleId().'</strong>" bien été prise en compte. </p>';
				}
				?>
		    </div>
		    
		    <div class="span6">
		    	<?php if($role != 'Admin'){ ?>

		    	<?php
		    	$rolesFils = array($role,'Visiteur');
		    	 echo $this->demandeRole($rolesFils); ?>

           			<?php } ?>

           			
		    </div>
		</div>
		<br/>
		<div class="alert alert-info">
	    	<button type="button" class="close" data-dismiss="alert">&times;</button>
	    	<p class="lead">Information</p>
    	    <dl class="dl-horizontal">
			    <dt>Rôle Utilisateur</dt>
			    <dd>Permet de consulter la collection et les parcours</dd>
			    <dt>Rôle Collection</dt>
			    <dd>Permet (en plus) d'alimenter la collection</dd>
			    <dt>Rôle Parcours</dt>
			    <dd>Permet (en plus) d'éditer des parcours</dd>
			    <dt>Rôle Admin</dt>
			    <dd>Tous les droits</dd>
		    </dl>
	    </div>
	</div>
</div>

<div style="clear:both;"></div>
