<!-- -->
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>
<!-- -->

<!--
<form method="get" action="login" accept-charset="UTF-8">
    <input style="margin-bottom: 15px;" type="text" placeholder="Email" id="email" name="email">
    <input style="margin-bottom: 15px;" type="password" placeholder="Mot de passe" id="password" name="password">
    <!--
    <input style="float: left;" type="checkbox" name="rememberme" id="rememberme" value="1">
    <label class="string optional" for="remember-me">Remember me</label>
    - ->
    <input class="btn btn-primary btn-block" type="submit" id="sign-in" value="Sign In">
    <input type="hidden" name="redirect" value=""/>
</form>
-->

Pas encore de compte ? <a href="<?php echo $this->url('zfcuser/register') ?>">S'enregistrer !</a><br><br>
