<!-- -->
<?php
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
    <?php foreach ($form as $element): ?>
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <dt><?php echo $this->formLabel($element) ?></dt>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <dd><?php echo $this->formButton($element) ?></dd>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
        <?php else: ?>
            <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
        <?php endif ?>
    <?php endforeach ?>
    </dl>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>
<!-- -->

<!--
<form class="form-horizontal">
    <fieldset>
    
        <legend>Inscription</legend>
        
        <div class="control-group">
            <label class="control-label">Nom</label>
            <div class="controls">
                <input id="nom" name="nom" placeholder="Nom" class="input-xlarge" required="" type="text">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Prenom</label>
            <div class="controls">
                <input id="prenom" name="prenom" placeholder="Prenom" class="input-xlarge" required="" type="text">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Email</label>
            <div class="controls">
                <input id="email" name="email" placeholder="Email" class="input-xlarge" required="" type="text">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Mots de passe</label>
            <div class="controls">
                <input id="password" name="password" placeholder="Mot de passe " class="input-xlarge" required="" type="password">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Confirmation</label>
            <div class="controls">
                <input id="confirmation" name="confirmation" placeholder="Confirmation" class="input-xlarge" required="" type="password">
            </div>
        </div>
        <div class="form-actions">
        
        <button class="btn btn-success">Inscription</button>
        
        </div>
    </fieldset>
</form>
<!-- -->