<?php

$title = 'Login';
$this->headTitle($title);
?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url("zfcuser/login"); ?>">Connexion</a></li>
    <li class="active"><a href="<?php echo $this->url("zfcuser/register"); ?>">Inscription</a></li>
</ul>

<div class="tab-content">
<?php
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');

            $form->setAttribute('class','form-horizontal');
            $form->get('display_name')->setAttribute('placeholder','Nom Prénom')->setLabel('Nom / prénom')->setLabelAttributes(array('class' => 'control-label'));
            $form->get('email')->setAttribute('placeholder','exemple@exemple.fr')->setLabelAttributes(array('class' => 'control-label'));
            $form->get('username')->setAttribute('placeholder','Login')->setLabel('Login')->setLabelAttributes(array('class' => 'control-label'));
            $form->get('password')->setAttribute('placeholder','******')->setLabel('Mot de passe')->setLabelAttributes(array('class' => 'control-label'));
            $form->get('passwordVerify')->setAttribute('placeholder','******')->setLabel('Vérification mot de passe')->setLabelAttributes(array('class' => 'control-label'));
            $form->get('submit')->setLabel('Valider')->setAttribute('class','btn btn-primary');
?>

<?php echo $this->form()->openTag($form) ?>
    <fieldset>
    <?php foreach ($form as $element): ?>
    
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
        <div class="control-group">
            <?php echo $this->formLabel($element); ?>
        <?php endif ?>
        
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <div class="form-actions">
                <?php echo $this->formButton($element) ?>

        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></div>
        <?php else: ?>
            <div class="controls"><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></div>
        <?php endif ?>
        
        </div>
    <?php endforeach ?>
    </fieldset>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
</div>
<!--
<form class="form-horizontal">
    <fieldset>
    
        <legend>Inscription</legend>
        
        <div class="control-group">
            <label class="control-label">Nom</label>
            <div class="controls">
                <input id="nom" name="nom" placeholder="Nom" class="input-xlarge" required="" type="text">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Prenom</label>
            <div class="controls">
                <input id="prenom" name="prenom" placeholder="Prenom" class="input-xlarge" required="" type="text">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Email</label>
            <div class="controls">
                <input id="email" name="email" placeholder="Email" class="input-xlarge" required="" type="text">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Mots de passe</label>
            <div class="controls">
                <input id="password" name="password" placeholder="Mot de passe " class="input-xlarge" required="" type="password">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Confirmation</label>
            <div class="controls">
                <input id="confirmation" name="confirmation" placeholder="Confirmation" class="input-xlarge" required="" type="password">
            </div>
        </div>
        <div class="form-actions">
        
        <button class="btn btn-success">Inscription</button>
        
        </div>
    </fieldset>
</form>
<!-- -->