<!-- -->
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->get('identity')->setAttributes(array('placeholder'=>'Login','style'=>'margin-bottom: 15px;'));
$form->get('credential')->setAttributes(array('placeholder'=>'Mot de passe','style'=>'margin-bottom: 10px;'));
$form->get('submit')->setLabel('Valider')->setAttribute('class','btn btn-success btn-block');

?>

<?php echo $this->form()->openTag($form) ?>

        <?php echo $this->formElementErrors($form->get('identity')) ?>


        <?php echo $this->formInput($form->get('identity')) ?>


        <?php echo $this->formInput($form->get('credential')) ?>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <?php echo $this->formButton($form->get('submit')) ?>
<br>
Pas encore de compte ? <a class="btn btn-success btn-block" href="<?php echo $this->url('zfcuser/register') ?>">S'enregistrer !</a>

<?php echo $this->form()->closeTag() ?>


