<?php

($type == 'media') ? $title = 'Création d\'un média' : $title = 'Création d\'un artefact';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/css/datepicker.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-wysihtml5.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/select2.css');
?>

<ul class="breadcrumb">
	<li><a href="<?php echo $this->url('page') ?>">Accueil</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('collection') ?>">Collection Numérique</a> <span class="divider">/</span></li>
    <li class="active"><?php echo $title; ?></li>
</ul>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Cette page permet de créer un nouvel élément dans la collection numérique
    	En choisissant le type d'élément que vous voulez créer, des champs à renseigner vont s'afficher.
    	</p>
    	<p>
    	L'éditeur de texte qui apparait à droite de l'écran permet de renseigner une description détaillée de l'élément qui vous donne la possibilité de rajouter toute donnée pertinent qui n'est pas prévue dans les champs prédéfinis.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header">
    <h1><i class="icon-tag"></i>  <?php echo $this->escapeHtml($title); ?> 
	<small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
</div>

<form id="selectform" class="form-horizontal">
	<div class="control-group">
		<label class="control-label" for="inputEmail">
			<?php ($type == 'media') ? $label='Types de média' : $label='Types d\'artefacts';
			echo $label; ?>
		</label>
	    <div class="controls">
			<select name="type" class="target">
				<option value="none">Veuillez choisir un type</option>
				<?php foreach ($types_elements as $current) : ?>
					<option value="<?php echo $current->id; ?>" <?php if($current->id == $type_element_id){echo 'selected="selected"';} ?>> <?php echo $this->escapeHtml($current->nom); ?> </option>
				<?php endforeach; ?>
			</select>
	    </div> 
	</div>
</form>
<hr>

<div id="containsform">
<?php if ($form) { 
	$form->setAttribute('action', $this->url('element/ajouter', array('type'=>$type, 'type_element_id' => $type_element_id)));
	$form->setAttribute('id','form');
	$form->setAttribute('class','form-horizontal no-submit');
	$form->setAttribute('method', 'post');
	$form->prepare();
	
	// Configure Errors Helper
	$errorsHelper  = $this->plugin('formelementerrors');

	echo $this->form()->openTag($form);
	?>
	
	<div class="row-fluid">
		<div class="span6">

			<?php foreach ($form as $element):
		 	if (!$element instanceof Zend\Form\Element\Button && 
				!$element instanceof Zend\Form\Element\Hidden &&
				!($element->getAttribute('type') == 'hidden') &&
				$element->getName() != 'description'): ?>
		 		<!-- Label du champ -->
		        <div class="control-group">
			        <label class="control-label">
			        	<?php echo $this->formLabel($element); ?>
			        </label>
			    	<div class="controls">
			    		<!-- Element du formulaire -->
			    		<div class="row-fluid">
			    			<div class="span11">
					    		<?php
					    		 if ($element instanceof Zend\Form\Element\File) { 
					    			echo $this->formFile($element);
					    		} elseif ($element instanceof Zend\Form\Element\Textarea) {
									echo $this->formTextarea($element);
								} elseif ($element->getAttribute('besoin_format')) {
									echo '
										<div class="row-fluid">
										<div class="span6">';
									$format = $form->get('format'.$element->getAttribute('name'));
									echo $this->formSelect($format);
									echo '</div>
										<div class="span6">';
									echo $this->formInput($element);
									echo '</div></div>';
								} elseif ($element instanceof DoctrineModule\Form\Element\ObjectSelect ) {
					    			echo $this->formSelect($element);
								} elseif ($element instanceof Zend\Form\Form && $element->getAttribute('type') == 'geoposition') {
									echo '<div class="row-fluid">
										<div class="span10"><blockquote>';
									foreach ( $element->getElements() as $element2 ):
               							 if ($element2 instanceof Zend\Form\Element\Textarea) {
                							echo $this->formLabel( $element2 ) ;
											echo $this->formTextarea($element2);
										} elseif ($element2 instanceof Zend\Form\Element\Text ) {
                							echo $this->formLabel( $element2 ) ;
											echo $this->formInput($element2);

										}
										echo $this->formElementErrors( $element2 ) ;
           							endforeach ;
           							echo '</blockquote></div><div class="span2">';
           							echo '<a href="" class="btn " ><i class="icon-map-marker"></i> </a>';
           							echo '</div></div>';
								} else {
				        			echo $this->formInput($element); 
								} ?> 
							</div>
							<div class="span1">
				        		<!-- Bulle d'information sur le champ -->
					        	<?php if ($element->getAttribute('description') != null) { ?>
						        	<a href="#" 
					        			id="<?php echo $element->getAttribute('name'); ?>"
					        			class="description"
					        			rel="popover"
					        			data-content="<?php echo $this->escapeHtml($element->getAttribute('description')); ?>"
					        			data-original-title="Description du champ"><i class="icon-question-sign"></i></a>  
					        	<?php } ?>
					        </div>
			        	</div>
				        <!-- Erreurs de validation du formulaire -->
				        <?php echo $this->formElementErrors($element); ?>
			        </div> <!-- /controls -->
			    </div> <!-- control-group -->
			<?php endif ?>
		
		<?php endforeach; ?>
		</div>
		
		<!-- Description -->
		<div class="span6 well">
		<?php foreach ($form as $element):
			if ($element->getName() == 'description'): ?>
	        	<!-- Editeur pour la description -->
	        	<?php echo $this->formInput($element); ?>
	        <?php endif; ?>
	    <?php endforeach; ?>
		</div>
	</div>
	
	<!-- Boutton -->
	<?php foreach ($form as $element):
		if ($element instanceof Zend\Form\Element\Button): ?>
	    	<!-- Bouton de validation du formulaire -->
	        <div class="form-actions"> 
	        	<?php echo $this->formSubmit($element); ?>
	        	<a href="<?php echo $this->url('collection/consulter') ?>" role="button" class="btn"> Annuler </a>
	    	</div>
	    <?php endif ?>
	
	<?php endforeach; ?>
	
	<?php echo $this->form()->closeTag(); ?>
<?php } else { ?>
	<div id="annuler">
	        <form class="form-horizontal">
		       	<div class="form-actions">
		       		<a href="<?php echo $this->url('collection/consulter') ?>" role="button" class="btn"> Annuler </a>
		       	</div>
	        </form>
	</div>
	<hr>
	<div id="containsform"></div>
<?php } ?>
</div>

<?php $this->inlineScript()->captureStart(); ?>

	$(function () { 

		$(".select").select2({
			placeholder: "Non renseigné",
			allowClear: true
		});

		// Modification de la valeur du select des types d'élément
		// On rappelle l'action element/ajouter pour récupérer le formulaire correspondant
		$(".target").change(function() {
		    if($("select option:selected").val()=='none') {
		    	var url="<?php echo $this->url('element/ajouter', array('type'=>$type))?>";
				$(location).attr('href',url);
		    } else {
			    var id = $("select option:selected").val();
		    	var url = '<?php echo $this->url('element/ajouter', array('type'=>$type, 'type_element_id' => '\'+id+\''))?>';
				$(location).attr('href',url);
		    }
		});

		// Gestion du date picker
	    $('.datepicker').datepicker({
	        language:'fr-FR',
	        format:'yyyy-dd-mm',
	        autoclose:true
	    });
    	

    	// Gestion des popover pour la description des champs
    	$(".description").popover({placement:'top', trigger:'hover'}); 
    	
    	// Gestion du wysihtml5
    	$('.wysihtml5-textarea').wysihtml5({
			locale: "fr-FR",
			image: false,
			stylesheets: ["<?php echo $this->basePath() . '/css/bootstrap.css';?>"],
			"events": {
				"load": function() { 
					$(editor.composer.iframe).wysihtml5_size_matters();
				}
			}
		});
		
		// Gestion de la précision des dates (jour, mois, année)
		$('.format_date').change(function() {
			var name = $(this).attr('data-input-name');
			$('input[name='+name+']').datepicker('remove');
			$('input[name='+name+']').val('');
			var format = $(this).val();
			if (format == 0) {
				$('input[name='+name+']').datepicker({
			        language:'fr-FR',
			        format:'yyyy-dd-mm',
			        autoclose:true,
			        minViewMode:0,
			        startView:0,
			    });
			} else if (format == 1) {
				$('input[name='+name+']').datepicker({
			        language:'fr-FR',
			        format:'yyyy-mm',
			        autoclose:true,
			        minViewMode:1,
			        startView:1,
			    });
			} else {
				$('input[name='+name+']').datepicker({
			        language:'fr-FR',
			        format:'yyyy',
			        autoclose:true,
			        minViewMode:2,
			        startView:2,
			    });
			}
		});
		
    });

<?php 
$this->inlineScript()->captureEnd();

$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-datepicker.js');
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js');
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap.file-input.js');
$this->headScript()->appendFile($this->basePath() . '/js/wysihtml5-0.3.0.min.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-wysihtml5.js') ; 
$this->headScript()->appendFile($this->basePath() . '/js/locales/bootstrap-wysihtml5.fr-FR.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/jquery.wysihtml5_size_matters.js');
$this->headScript()->appendFile($this->basePath() . '/js/select2.js');
$this->headScript()->appendFile($this->basePath() . '/js/locales/select2_locale_fr.js') ;
?>